window.SEED_CARDS = [
  {
    id: "c001",
    text: "Aplikasi yang sering dibuka",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c002",
    text: "Emoji yang sering dipakai",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c003",
    text: "Reaction meme",
    lang: "MIX",
    code: "H",
    enabled: true,
  },
  {
    id: "c004",
    text: "Jenis video YouTube",
    lang: "MIX",
    code: "E",
    enabled: true,
  },
  {
    id: "c005",
    text: "Nama playlist",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c006",
    text: "Lagu buat karaoke",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c007",
    text: "Lagu buat semangat",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c008",
    text: "Genre musik",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c009",
    text: "Topik podcast",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c010",
    text: "Film animasi",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  {
    id: "c011",
    text: "Karakter kartun",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c012",
    text: "Superhero",
    lang: "EN",
    code: "F",
    enabled: true,
  },
  {
    id: "c013",
    text: "Fictional villain",
    lang: "EN",
    code: "C",
    enabled: true,
  },
  {
    id: "c014",
    text: "Anime character",
    lang: "EN",
    code: "A",
    enabled: true,
  },
  {
    id: "c015",
    text: "Video game",
    lang: "EN",
    code: "F",
    enabled: true,
  },
  {
    id: "c016",
    text: "Game mobile",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c017",
    text: "Board game",
    lang: "EN",
    code: "H",
    enabled: true,
  },
  {
    id: "c018",
    text: "Website",
    lang: "EN",
    code: "E",
    enabled: true,
  },
  {
    id: "c019",
    text: "Fitur media sosial",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c020",
    text: "Filter kamera",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c021",
    text: "Stiker chat",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c022",
    text: "Sound effect",
    lang: "EN",
    code: "B",
    enabled: true,
  },
  {
    id: "c023",
    text: "Nama grup chat",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c024",
    text: "Nama Wi-Fi lucu",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  {
    id: "c025",
    text: "Caption foto",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c026",
    text: "Hashtag",
    lang: "EN",
    code: "F",
    enabled: true,
  },
  {
    id: "c027",
    text: "Gaya username",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c028",
    text: "Tech gadget",
    lang: "EN",
    code: "A",
    enabled: true,
  },
  {
    id: "c029",
    text: "Keyboard shortcut",
    lang: "EN",
    code: "F",
    enabled: true,
  },
  {
    id: "c030",
    text: "Notification sound",
    lang: "EN",
    code: "C",
    enabled: true,
  },
  {
    id: "c031",
    text: "Snack minimarket",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c032",
    text: "Minuman dingin",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c033",
    text: "Topping pizza",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c034",
    text: "Rasa es krim",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c035",
    text: "Rasa mi instan",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c036",
    text: "Street food",
    lang: "EN",
    code: "B",
    enabled: true,
  },
  {
    id: "c037",
    text: "Gorengan",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c038",
    text: "Jenis sambal",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  {
    id: "c039",
    text: "Bakery item",
    lang: "EN",
    code: "A",
    enabled: true,
  },
  {
    id: "c040",
    text: "Buah",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c041",
    text: "Sayur",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c042",
    text: "Dessert",
    lang: "EN",
    code: "A",
    enabled: true,
  },
  {
    id: "c043",
    text: "Menu sarapan",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c044",
    text: "Midnight snack",
    lang: "EN",
    code: "C",
    enabled: true,
  },
  {
    id: "c045",
    text: "Minuman kafe",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c046",
    text: "Topping boba",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c047",
    text: "Makanan pedas",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c048",
    text: "Comfort food",
    lang: "EN",
    code: "G",
    enabled: true,
  },
  {
    id: "c049",
    text: "Makanan saat hujan",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c050",
    text: "Isi bekal",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c051",
    text: "Camilan nonton",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c052",
    text: "Makanan warna merah",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  {
    id: "c053",
    text: "Makanan renyah",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c054",
    text: "Makanan manis",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c055",
    text: "Menu warung",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c056",
    text: "Mata pelajaran",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c057",
    text: "Alasan telat",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c058",
    text: "Kalimat guru",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c059",
    text: "Alat tulis",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c060",
    text: "Isi tas sekolah",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c061",
    text: "Ekstrakurikuler",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c062",
    text: "Pembuka presentasi",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c063",
    text: "Peran di tugas kelompok",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c064",
    text: "Reaksi habis ujian",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c065",
    text: "Aktivitas jam istirahat",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c066",
    text: "Jajanan kantin",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  {
    id: "c067",
    text: "Acara sekolah",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c068",
    text: "Study tip",
    lang: "EN",
    code: "F",
    enabled: true,
  },
  {
    id: "c069",
    text: "Gangguan saat belajar",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c070",
    text: "Alasan kamera mati",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c071",
    text: "Isi meja belajar",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c072",
    text: "Jenis catatan",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c073",
    text: "Alat buat presentasi",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c074",
    text: "Tempat belajar",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c075",
    text: "Target minggu ini",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c076",
    text: "Hal yang sering lupa dikumpulkan",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c077",
    text: "Aplikasi produktivitas",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c078",
    text: "Cara fokus",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c079",
    text: "Reward habis belajar",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c080",
    text: "Kalimat penyemangat",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  {
    id: "c081",
    text: "Benda di kamar",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c082",
    text: "Benda di kamar mandi",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c083",
    text: "Pekerjaan rumah",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c084",
    text: "Barang yang sering hilang",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c085",
    text: "Isi backpack",
    lang: "MIX",
    code: "F",
    enabled: true,
  },
  {
    id: "c086",
    text: "Aktivitas saat hujan",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c087",
    text: "Aktivitas weekend",
    lang: "MIX",
    code: "H",
    enabled: true,
  },
  {
    id: "c088",
    text: "Hobi",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c089",
    text: "Olahraga",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c090",
    text: "Nama hewan peliharaan",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c091",
    text: "Kelakuan kucing",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c092",
    text: "Pose tidur kucing",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c093",
    text: "Alasan kucing mengeong",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c094",
    text: "Benda favorit kucing",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  {
    id: "c095",
    text: "Suara hewan",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c096",
    text: "Hewan kebun binatang",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c097",
    text: "Makhluk fantasi",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c098",
    text: "Jenis cuaca",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c099",
    text: "Warna",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c100",
    text: "Pakaian",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c101",
    text: "Jenis sepatu",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c102",
    text: "Jenis topi",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c103",
    text: "Aksesori",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c104",
    text: "Gaya rambut",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c105",
    text: "Dekorasi kamar",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c106",
    text: "Furniture",
    lang: "EN",
    code: "B",
    enabled: true,
  },
  {
    id: "c107",
    text: "Benda di dapur",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c108",
    text: "Benda di ruang tamu",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  {
    id: "c109",
    text: "Jenis transportasi",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c110",
    text: "Tempat nongkrong",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c111",
    text: "Tempat buat foto",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c112",
    text: "Benda yang ada di meja",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c113",
    text: "Barang yang wajib dibawa",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c114",
    text: "Aktivitas tanpa internet",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c115",
    text: "Hadiah kecil yang menyenangkan",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c116",
    text: "Hal yang bikin auto senyum",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c117",
    text: "Hal yang bikin auto panik",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c118",
    text: "Hal yang bikin malu sendiri",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c119",
    text: "Hal yang bikin FOMO",
    lang: "MIX",
    code: "E",
    enabled: true,
  },
  {
    id: "c120",
    text: "Hal yang bikin mood naik",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c121",
    text: "Hal yang bikin mood turun",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c122",
    text: "Tiny win",
    lang: "EN",
    code: "D",
    enabled: true,
  },
  {
    id: "c123",
    text: "Main character moment",
    lang: "EN",
    code: "A",
    enabled: true,
  },
  {
    id: "c124",
    text: "NPC behavior",
    lang: "EN",
    code: "F",
    enabled: true,
  },
  {
    id: "c125",
    text: "Plot twist kehidupan",
    lang: "MIX",
    code: "C",
    enabled: true,
  },
  {
    id: "c126",
    text: "Skill yang pengin di-unlock",
    lang: "MIX",
    code: "A",
    enabled: true,
  },
  {
    id: "c127",
    text: "Side quest weekend",
    lang: "MIX",
    code: "F",
    enabled: true,
  },
  {
    id: "c128",
    text: "Barang yang selalu lupa dibawa",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c129",
    text: "Kata slang",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c130",
    text: "Singkatan chat",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c131",
    text: "Cara bilang iya",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c132",
    text: "Cara bilang nggak",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c133",
    text: "Jawaban aman saat bingung",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c134",
    text: "Kalimat teman receh",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c135",
    text: "Panggilan teman",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c136",
    text: "Alasan batal pergi",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  {
    id: "c137",
    text: "Alasan bangun kesiangan",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c138",
    text: "Alasan baterai habis",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c139",
    text: "Hal yang dilakukan saat Wi-Fi mati",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c140",
    text: "Random thought yang harmless",
    lang: "MIX",
    code: "A",
    enabled: true,
  },
  {
    id: "c141",
    text: "Negara",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c142",
    text: "Kota",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c143",
    text: "Planet",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c144",
    text: "Dinosaurus",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c145",
    text: "Jenis pohon",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c146",
    text: "Bunga",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c147",
    text: "Alat musik",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c148",
    text: "Pekerjaan",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c149",
    text: "Bahasa",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c150",
    text: "Tanda baca",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  {
    id: "c151",
    text: "Alasan belum bales chat",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c152",
    text: "Intronya lagu Indonesia pop",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c153",
    text: "Hal yang di-screenshot tapi nggak pernah dibaca lagi",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c154",
    text: "Gaya jalan orang pas kepleset",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c155",
    text: "Mimpi buruk waktu kecil",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c156",
    text: "Barang di keranjang olshop yang cuma di-checkout pas gratis ongkir",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c157",
    text: "Kalimat yang diucap pas nyenggol tiang",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c158",
    text: "Suara misterius jam 2 malam",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c159",
    text: "Cita-cita random pas TK",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c160",
    text: "Aktivitas pas lagi pura-pura sibuk",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c161",
    text: "Topik pembicaraan bapak-bapak ronda",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  {
    id: "c162",
    text: "Hal yang dilakukan kalau salah masuk toilet",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c163",
    text: "Cemilan yang abis duluan sebelum filmnya mulai",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c164",
    text: "Kejadian konyol pas mati lampu",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c165",
    text: "Alasan pura-pura tidur pas naik angkot",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c166",
    text: "Kalimat 'Sip' versi bahasa daerah",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c167",
    text: "Hal yang dicari pas pertama kali datang ke kondangan",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c168",
    text: "Gaya foto bareng anak perkuliahan",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c169",
    text: "Mitos lokal yang bikin takut mandi malam",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c170",
    text: "Kebiasaan buruk pas lagi mandi",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c171",
    text: "Kata pertama yang diucap pas dompet ketinggalan",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c172",
    text: "Nama hewan yang suaranya mirip instrumen",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c173",
    text: "Benda yang dipakai buat ngaganjel pintu",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c174",
    text: "Guilty pleasure makanan kombinasi aneh",
    lang: "MIX",
    code: "G",
    enabled: true,
  },
  {
    id: "c175",
    text: "Alasan batalin rencana wacana",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  {
    id: "c176",
    text: "Lagu yang bikin tiba-tiba serasa di klip musik",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c177",
    text: "Penyesalan terbesar abis potong rambut",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c178",
    text: "Eksperimen aneh waktu SD",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c179",
    text: "Hal pertama yang dibeli kalau mendadak menang lotre",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c180",
    text: "Gaya mengetik di WhatsApp yang paling ngeselin",
    lang: "MIX",
    code: "F",
    enabled: true,
  },
  {
    id: "c181",
    text: "Sound TikTok yang nempel terus di otak",
    lang: "MIX",
    code: "C",
    enabled: true,
  },
  {
    id: "c182",
    text: "Alasan orang tiba-tiba senyum-senyum sendiri di jalan",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c183",
    text: "Barang unik yang dipajang di dashboard mobil",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c184",
    text: "Superpower konyol tapi sangat berguna di kehidupan sehari-hari",
    lang: "MIX",
    code: "B",
    enabled: true,
  },
  {
    id: "c185",
    text: "Jawaban pas ditanya 'Kapan nikah?'",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c186",
    text: "Camilan wajib pas lagi nge-game",
    lang: "MIX",
    code: "E",
    enabled: true,
  },
  {
    id: "c187",
    text: "Aktivitas pas lagi menunggu antrean panjang",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c188",
    text: "Hal yang cuma dilakukan pas sendirian di rumah",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c189",
    text: "Nama stiker WA yang paling sering dikirim pas grup sepi",
    lang: "MIX",
    code: "D",
    enabled: true,
  },
  {
    id: "c190",
    text: "Alasan klasik ganti foto profil",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c191",
    text: "Hal yang bikin mikir 'Gua dewasa banget sekarang'",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c192",
    text: "Drama sepele yang bikin heboh satu tongkrongan",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c193",
    text: "Benda yang kalau jatuh bunyinya kenceng banget",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c194",
    text: "Gaya jalan saat kepanasan di siang bolong",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c195",
    text: "Momen paling awkward sama driver ojol",
    lang: "MIX",
    code: "C",
    enabled: true,
  },
  {
    id: "c196",
    text: "Barang hilang yang tiba-tiba muncul di tempat tak terduga",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c197",
    text: "Pura-pura ngerti padahal nggak paham sama sekali tentang...",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c198",
    text: "Hal yang dilakukan pas keabisan bahan obrolan sama gebetan",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c199",
    text: "Kejadian konyol pas nyoba resep masakan baru",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c200",
    text: "Aksi heroik sepele yang bikin merasa jadi pahlawan",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  // Tambahan 100 kartu Anomia: c201-c300
// Tempelkan blok ini sebelum `];` pada window.SEED_CARDS.

// ===== Tema 1: Nusantara =====
{
  id: "c201",
  text: "Makanan khas Indonesia",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c202",
  text: "Kota wisata di Indonesia",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c203",
  text: "Pulau di Indonesia",
  lang: "ID",
  code: "A",
  enabled: true,
},
{
  id: "c204",
  text: "Tarian tradisional Indonesia",
  lang: "ID",
  code: "C",
  enabled: true,
},
{
  id: "c205",
  text: "Alat musik tradisional Indonesia",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c206",
  text: "Bahasa daerah Indonesia",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c207",
  text: "Oleh-oleh khas daerah",
  lang: "ID",
  code: "F",
  enabled: true,
},
{
  id: "c208",
  text: "Tempat wisata alam Indonesia",
  lang: "ID",
  code: "G",
  enabled: true,
},
{
  id: "c209",
  text: "Tokoh legenda Nusantara",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c210",
  text: "Permainan tradisional Indonesia",
  lang: "ID",
  code: "B",
  enabled: true,
},

// ===== Tema 2: Travel =====
{
  id: "c211",
  text: "Barang wajib di koper",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c212",
  text: "Aktivitas di bandara",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c213",
  text: "Tempat yang ada di bandara",
  lang: "ID",
  code: "A",
  enabled: true,
},
{
  id: "c214",
  text: "Destinasi liburan luar negeri",
  lang: "ID",
  code: "B",
  enabled: true,
},
{
  id: "c215",
  text: "Aktivitas di pantai",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c216",
  text: "Perlengkapan camping",
  lang: "MIX",
  code: "H",
  enabled: true,
},
{
  id: "c217",
  text: "Landmark dunia terkenal",
  lang: "MIX",
  code: "C",
  enabled: true,
},
{
  id: "c218",
  text: "Barang yang dibeli sebagai suvenir",
  lang: "ID",
  code: "E",
  enabled: true,
},
{
  id: "c219",
  text: "Masalah kecil saat traveling",
  lang: "MIX",
  code: "F",
  enabled: true,
},
{
  id: "c220",
  text: "Alasan koper jadi overweight",
  lang: "MIX",
  code: "E",
  enabled: true,
},

// ===== Tema 3: Film & TV =====
{
  id: "c221",
  text: "Genre film",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c222",
  text: "Judul film horor",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c223",
  text: "Karakter film terkenal",
  lang: "ID",
  code: "A",
  enabled: true,
},
{
  id: "c224",
  text: "Film yang punya sekuel",
  lang: "ID",
  code: "C",
  enabled: true,
},
{
  id: "c225",
  text: "Aktor Indonesia",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c226",
  text: "Aktris Indonesia",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c227",
  text: "Profesi di balik layar film",
  lang: "ID",
  code: "F",
  enabled: true,
},
{
  id: "c228",
  text: "Benda yang ada di bioskop",
  lang: "ID",
  code: "G",
  enabled: true,
},
{
  id: "c229",
  text: "Acara TV kompetisi",
  lang: "ID",
  code: "A",
  enabled: true,
},
{
  id: "c230",
  text: "Film bertema luar angkasa",
  lang: "ID",
  code: "G",
  enabled: true,
},

// ===== Tema 4: Gaming =====
{
  id: "c231",
  text: "Genre game",
  lang: "MIX",
  code: "D",
  enabled: true,
},
{
  id: "c232",
  text: "Karakter video game",
  lang: "MIX",
  code: "H",
  enabled: true,
},
{
  id: "c233",
  text: "Item dalam game",
  lang: "MIX",
  code: "A",
  enabled: true,
},
{
  id: "c234",
  text: "Musuh dalam game",
  lang: "MIX",
  code: "B",
  enabled: true,
},
{
  id: "c235",
  text: "Game multiplayer",
  lang: "MIX",
  code: "D",
  enabled: true,
},
{
  id: "c236",
  text: "Hal yang bikin rage quit",
  lang: "MIX",
  code: "H",
  enabled: true,
},
{
  id: "c237",
  text: "Perangkat gaming",
  lang: "MIX",
  code: "C",
  enabled: true,
},
{
  id: "c238",
  text: "Tombol keyboard yang sering dipakai saat gaming",
  lang: "MIX",
  code: "E",
  enabled: true,
},
{
  id: "c239",
  text: "Hadiah dalam game",
  lang: "MIX",
  code: "F",
  enabled: true,
},
{
  id: "c240",
  text: "Lokasi yang sering ada di game",
  lang: "MIX",
  code: "G",
  enabled: true,
},

// ===== Tema 5: Olahraga =====
{
  id: "c241",
  text: "Cabang olahraga Olimpiade",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c242",
  text: "Posisi pemain sepak bola",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c243",
  text: "Peralatan olahraga",
  lang: "ID",
  code: "A",
  enabled: true,
},
{
  id: "c244",
  text: "Klub sepak bola",
  lang: "ID",
  code: "C",
  enabled: true,
},
{
  id: "c245",
  text: "Gerakan olahraga",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c246",
  text: "Olahraga air",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c247",
  text: "Olahraga raket",
  lang: "ID",
  code: "F",
  enabled: true,
},
{
  id: "c248",
  text: "Benda di stadion",
  lang: "ID",
  code: "G",
  enabled: true,
},
{
  id: "c249",
  text: "Istilah sepak bola",
  lang: "ID",
  code: "B",
  enabled: true,
},
{
  id: "c250",
  text: "Alasan wasit menghentikan pertandingan",
  lang: "ID",
  code: "H",
  enabled: true,
},

// ===== Tema 6: Sains & Alam =====
{
  id: "c251",
  text: "Alat di laboratorium",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c252",
  text: "Hewan laut",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c253",
  text: "Fenomena alam",
  lang: "ID",
  code: "A",
  enabled: true,
},
{
  id: "c254",
  text: "Bagian tubuh manusia",
  lang: "ID",
  code: "B",
  enabled: true,
},
{
  id: "c255",
  text: "Organ tubuh manusia",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c256",
  text: "Unsur kimia",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c257",
  text: "Sumber energi",
  lang: "ID",
  code: "C",
  enabled: true,
},
{
  id: "c258",
  text: "Benda yang bisa mengapung",
  lang: "ID",
  code: "E",
  enabled: true,
},
{
  id: "c259",
  text: "Hewan nokturnal",
  lang: "ID",
  code: "F",
  enabled: true,
},
{
  id: "c260",
  text: "Benda di luar angkasa",
  lang: "ID",
  code: "D",
  enabled: true,
},

// ===== Tema 7: Kantor & Kerja =====
{
  id: "c261",
  text: "Jabatan di kantor",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c262",
  text: "Alasan meeting molor",
  lang: "MIX",
  code: "H",
  enabled: true,
},
{
  id: "c263",
  text: "Barang di meja kantor",
  lang: "ID",
  code: "A",
  enabled: true,
},
{
  id: "c264",
  text: "Aplikasi untuk kerja",
  lang: "ID",
  code: "C",
  enabled: true,
},
{
  id: "c265",
  text: "Kalimat yang sering muncul saat meeting",
  lang: "MIX",
  code: "D",
  enabled: true,
},
{
  id: "c266",
  text: "Barang di pantry kantor",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c267",
  text: "Profesi yang memakai seragam",
  lang: "ID",
  code: "F",
  enabled: true,
},
{
  id: "c268",
  text: "Aktivitas saat jam makan siang kantor",
  lang: "ID",
  code: "G",
  enabled: true,
},
{
  id: "c269",
  text: "Alasan izin tidak masuk kerja",
  lang: "ID",
  code: "E",
  enabled: true,
},
{
  id: "c270",
  text: "File yang sering dicari di laptop kantor",
  lang: "ID",
  code: "H",
  enabled: true,
},

// ===== Tema 8: Sosial & Tongkrongan =====
{
  id: "c271",
  text: "Topik first date",
  lang: "MIX",
  code: "D",
  enabled: true,
},
{
  id: "c272",
  text: "Hadiah ulang tahun",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c273",
  text: "Aktivitas saat reuni",
  lang: "ID",
  code: "A",
  enabled: true,
},
{
  id: "c274",
  text: "Tipe teman di tongkrongan",
  lang: "ID",
  code: "B",
  enabled: true,
},
{
  id: "c275",
  text: "Acara keluarga",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c276",
  text: "Kalimat setelah salah kirim chat",
  lang: "MIX",
  code: "H",
  enabled: true,
},
{
  id: "c277",
  text: "Barang yang dibawa saat main ke rumah teman",
  lang: "ID",
  code: "C",
  enabled: true,
},
{
  id: "c278",
  text: "Alasan pulang duluan dari tongkrongan",
  lang: "ID",
  code: "E",
  enabled: true,
},
{
  id: "c279",
  text: "Hal yang bikin grup chat mendadak ramai",
  lang: "MIX",
  code: "F",
  enabled: true,
},
{
  id: "c280",
  text: "Aktivitas saat nongkrong tanpa HP",
  lang: "MIX",
  code: "G",
  enabled: true,
},

// ===== Tema 9: Horor & Misteri =====
{
  id: "c281",
  text: "Makhluk horor",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c282",
  text: "Tempat menyeramkan",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c283",
  text: "Benda di rumah kosong",
  lang: "ID",
  code: "A",
  enabled: true,
},
{
  id: "c284",
  text: "Suara khas film horor",
  lang: "ID",
  code: "C",
  enabled: true,
},
{
  id: "c285",
  text: "Hal aneh di rumah tengah malam",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c286",
  text: "Benda untuk melawan monster fiksi",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c287",
  text: "Kesalahan klasik di film horor",
  lang: "ID",
  code: "F",
  enabled: true,
},
{
  id: "c288",
  text: "Kostum Halloween",
  lang: "MIX",
  code: "G",
  enabled: true,
},
{
  id: "c289",
  text: "Urban legend",
  lang: "MIX",
  code: "B",
  enabled: true,
},
{
  id: "c290",
  text: "Cara kabur dari zombie",
  lang: "ID",
  code: "D",
  enabled: true,
},

// ===== Tema 10: Masa Depan & Fantasi =====
{
  id: "c291",
  text: "Planet fiksi",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c292",
  text: "Pekerjaan masa depan",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c293",
  text: "Gadget masa depan",
  lang: "MIX",
  code: "A",
  enabled: true,
},
{
  id: "c294",
  text: "Kekuatan super",
  lang: "ID",
  code: "B",
  enabled: true,
},
{
  id: "c295",
  text: "Kendaraan futuristik",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c296",
  text: "Benda di pesawat luar angkasa",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c297",
  text: "Nama robot fiksi",
  lang: "MIX",
  code: "C",
  enabled: true,
},
{
  id: "c298",
  text: "Alasan alien datang ke Bumi",
  lang: "ID",
  code: "E",
  enabled: true,
},
{
  id: "c299",
  text: "Barang yang dibawa ke Mars",
  lang: "ID",
  code: "F",
  enabled: true,
},
{
  id: "c300",
  text: "Benda yang tidak boleh dibawa ke mesin waktu",
  lang: "ID",
  code: "E",
  enabled: true,
}
];
