window.SEED_CARDS = [
  {
    id: "c001",
    text: "Aplikasi yang sering dibuka",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c002",
    text: "Emoji yang sering dipakai",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c003",
    text: "Reaction meme",
    lang: "MIX",
    code: "H",
    enabled: true,
  },
  {
    id: "c004",
    text: "Jenis video YouTube",
    lang: "MIX",
    code: "E",
    enabled: true,
  },
  {
    id: "c005",
    text: "Nama playlist",
    lang: "ID",
    code: "B",
    chaos: "Wajib tos sebelum jawab!",
    enabled: true,
  },
  {
    id: "c006",
    text: "Lagu buat karaoke",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c007",
    text: "Lagu buat semangat",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c008",
    text: "Genre musik",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c009",
    text: "Topik podcast",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c010",
    text: "Film animasi",
    lang: "ID",
    code: "D",
    chaos: "Jawab sambil berdiri!",
    enabled: true,
  },
  {
    id: "c011",
    text: "Karakter kartun",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c012",
    text: "Superhero",
    lang: "EN",
    code: "F",
    enabled: true,
  },
  {
    id: "c013",
    text: "Fictional villain",
    lang: "EN",
    code: "C",
    enabled: true,
  },
  {
    id: "c014",
    text: "Anime character",
    lang: "EN",
    code: "A",
    enabled: true,
  },
  {
    id: "c015",
    text: "Video game",
    lang: "EN",
    code: "F",
    chaos: "Semua tepuk tangan dulu!",
    enabled: true,
  },
  {
    id: "c016",
    text: "Game mobile",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c017",
    text: "Board game",
    lang: "EN",
    code: "H",
    enabled: true,
  },
  {
    id: "c018",
    text: "Website",
    lang: "EN",
    code: "E",
    enabled: true,
  },
  {
    id: "c019",
    text: "Fitur media sosial",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c020",
    text: "Filter kamera",
    lang: "ID",
    code: "G",
    chaos: "Jawaban pakai suara robot!",
    enabled: true,
  },
  {
    id: "c021",
    text: "Stiker chat",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c022",
    text: "Sound effect",
    lang: "EN",
    code: "B",
    enabled: true,
  },
  {
    id: "c023",
    text: "Nama grup chat",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c024",
    text: "Nama Wi-Fi lucu",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  {
    id: "c025",
    text: "Caption foto",
    lang: "ID",
    code: "A",
    chaos: "Yang telat jawab, joget dulu!",
    enabled: true,
  },
  {
    id: "c026",
    text: "Hashtag",
    lang: "EN",
    code: "F",
    enabled: true,
  },
  {
    id: "c027",
    text: "Gaya username",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c028",
    text: "Tech gadget",
    lang: "EN",
    code: "A",
    enabled: true,
  },
  {
    id: "c029",
    text: "Keyboard shortcut",
    lang: "EN",
    code: "F",
    enabled: true,
  },
  {
    id: "c030",
    text: "Notification sound",
    lang: "EN",
    code: "C",
    chaos: "Semua teriak \"Anomia!\" bareng!",
    enabled: true,
  },
  {
    id: "c031",
    text: "Snack minimarket",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c032",
    text: "Minuman dingin",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c033",
    text: "Topping pizza",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c034",
    text: "Rasa es krim",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c035",
    text: "Rasa mi instan",
    lang: "ID",
    code: "E",
    chaos: "Jawab sambil menirukan kucing!",
    enabled: true,
  },
  {
    id: "c036",
    text: "Street food",
    lang: "EN",
    code: "B",
    enabled: true,
  },
  {
    id: "c037",
    text: "Gorengan",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c038",
    text: "Jenis sambal",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  {
    id: "c039",
    text: "Bakery item",
    lang: "EN",
    code: "A",
    enabled: true,
  },
  {
    id: "c040",
    text: "Buah",
    lang: "ID",
    code: "F",
    chaos: "Yang salah jawab, nyanyi dikit!",
    enabled: true,
  },
  {
    id: "c041",
    text: "Sayur",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c042",
    text: "Dessert",
    lang: "EN",
    code: "A",
    enabled: true,
  },
  {
    id: "c043",
    text: "Menu sarapan",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c044",
    text: "Midnight snack",
    lang: "EN",
    code: "C",
    enabled: true,
  },
  {
    id: "c045",
    text: "Minuman kafe",
    lang: "ID",
    code: "H",
    chaos: "Semua wajib ketawa 3 detik!",
    enabled: true,
  },
  {
    id: "c046",
    text: "Topping boba",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c047",
    text: "Makanan pedas",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c048",
    text: "Comfort food",
    lang: "EN",
    code: "G",
    enabled: true,
  },
  {
    id: "c049",
    text: "Makanan saat hujan",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c050",
    text: "Isi bekal",
    lang: "ID",
    code: "B",
    chaos: "Jawaban dibisikkan dulu ke sebelah!",
    enabled: true,
  },
  {
    id: "c051",
    text: "Camilan nonton",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c052",
    text: "Makanan warna merah",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  {
    id: "c053",
    text: "Makanan renyah",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c054",
    text: "Makanan manis",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c055",
    text: "Menu warung",
    lang: "ID",
    code: "C",
    chaos: "Jawab pakai logat daerah!",
    enabled: true,
  },
  {
    id: "c056",
    text: "Mata pelajaran",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c057",
    text: "Alasan telat",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c058",
    text: "Kalimat guru",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c059",
    text: "Alat tulis",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c060",
    text: "Isi tas sekolah",
    lang: "ID",
    code: "E",
    chaos: "Semua pemain tos silang!",
    enabled: true,
  },
  {
    id: "c061",
    text: "Ekstrakurikuler",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c062",
    text: "Pembuka presentasi",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c063",
    text: "Peran di tugas kelompok",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c064",
    text: "Reaksi habis ujian",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c065",
    text: "Aktivitas jam istirahat",
    lang: "ID",
    code: "G",
    chaos: "Yang menang, kasih jempol!",
    enabled: true,
  },
  {
    id: "c066",
    text: "Jajanan kantin",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  {
    id: "c067",
    text: "Acara sekolah",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c068",
    text: "Study tip",
    lang: "EN",
    code: "F",
    enabled: true,
  },
  {
    id: "c069",
    text: "Gangguan saat belajar",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c070",
    text: "Alasan kamera mati",
    lang: "ID",
    code: "A",
    chaos: "Jawab sambil pasang muka kaget!",
    enabled: true,
  },
  {
    id: "c071",
    text: "Isi meja belajar",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c072",
    text: "Jenis catatan",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c073",
    text: "Alat buat presentasi",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c074",
    text: "Tempat belajar",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c075",
    text: "Target minggu ini",
    lang: "ID",
    code: "B",
    chaos: "Semua bersorak \"Huuu!\" dulu!",
    enabled: true,
  },
  {
    id: "c076",
    text: "Tugas sering lupa dikumpul",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c077",
    text: "Aplikasi produktivitas",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c078",
    text: "Cara fokus",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c079",
    text: "Reward habis belajar",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c080",
    text: "Kalimat penyemangat",
    lang: "ID",
    code: "D",
    chaos: "Jawab sambil pegang hidung!",
    enabled: true,
  },
  {
    id: "c081",
    text: "Benda di kamar",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c082",
    text: "Benda di kamar mandi",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c083",
    text: "Pekerjaan rumah",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c084",
    text: "Barang yang sering hilang",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c085",
    text: "Isi backpack",
    lang: "MIX",
    code: "F",
    chaos: "Yang telat jawab, cengiran lebar!",
    enabled: true,
  },
  {
    id: "c086",
    text: "Aktivitas saat hujan",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c087",
    text: "Aktivitas weekend",
    lang: "MIX",
    code: "H",
    enabled: true,
  },
  {
    id: "c088",
    text: "Hobi",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c089",
    text: "Olahraga",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c090",
    text: "Nama hewan peliharaan",
    lang: "ID",
    code: "G",
    chaos: "Semua wajib high-five tetangga!",
    enabled: true,
  },
  {
    id: "c091",
    text: "Kelakuan kucing",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c092",
    text: "Pose tidur kucing",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c093",
    text: "Alasan kucing mengeong",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c094",
    text: "Benda favorit kucing",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  {
    id: "c095",
    text: "Suara hewan",
    lang: "ID",
    code: "A",
    chaos: "Jawaban wajib pakai gaya drama!",
    enabled: true,
  },
  {
    id: "c096",
    text: "Hewan kebun binatang",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c097",
    text: "Makhluk fantasi",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c098",
    text: "Jenis cuaca",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c099",
    text: "Warna",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c100",
    text: "Pakaian",
    lang: "ID",
    code: "C",
    chaos: "Yang salah jawab, tepuk jidat!",
    enabled: true,
  },
  {
    id: "c101",
    text: "Jenis sepatu",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c102",
    text: "Jenis topi",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c103",
    text: "Aksesori",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c104",
    text: "Gaya rambut",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c105",
    text: "Dekorasi kamar",
    lang: "ID",
    code: "E",
    chaos: "Semua diam 2 detik dulu!",
    enabled: true,
  },
  {
    id: "c106",
    text: "Furniture",
    lang: "EN",
    code: "B",
    enabled: true,
  },
  {
    id: "c107",
    text: "Benda di dapur",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c108",
    text: "Benda di ruang tamu",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  {
    id: "c109",
    text: "Jenis transportasi",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c110",
    text: "Tempat nongkrong",
    lang: "ID",
    code: "F",
    chaos: "Jawab sambil menunjuk langit!",
    enabled: true,
  },
  {
    id: "c111",
    text: "Tempat buat foto",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c112",
    text: "Benda di atas meja",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c113",
    text: "Barang yang wajib dibawa",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c114",
    text: "Aktivitas tanpa internet",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c115",
    text: "Hadiah kecil yang menyenangkan",
    lang: "ID",
    code: "H",
    chaos: "Yang menang, teriak \"Yeay!\"!",
    enabled: true,
  },
  {
    id: "c116",
    text: "Hal bikin auto senyum",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c117",
    text: "Hal bikin auto panik",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c118",
    text: "Hal bikin malu sendiri",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c119",
    text: "Hal yang bikin FOMO",
    lang: "MIX",
    code: "E",
    enabled: true,
  },
  {
    id: "c120",
    text: "Hal bikin mood naik",
    lang: "ID",
    code: "B",
    chaos: "Semua pemain putar badan dulu!",
    enabled: true,
  },
  {
    id: "c121",
    text: "Hal bikin mood turun",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c122",
    text: "Tiny win",
    lang: "EN",
    code: "D",
    enabled: true,
  },
  {
    id: "c123",
    text: "Main character moment",
    lang: "EN",
    code: "A",
    enabled: true,
  },
  {
    id: "c124",
    text: "NPC behavior",
    lang: "EN",
    code: "F",
    enabled: true,
  },
  {
    id: "c125",
    text: "Plot twist kehidupan",
    lang: "MIX",
    code: "C",
    chaos: "Jawaban wajib dramatis banget!",
    enabled: true,
  },
  {
    id: "c126",
    text: "Skill yang pengin di-unlock",
    lang: "MIX",
    code: "A",
    enabled: true,
  },
  {
    id: "c127",
    text: "Side quest weekend",
    lang: "MIX",
    code: "F",
    enabled: true,
  },
  {
    id: "c128",
    text: "Barang selalu lupa dibawa",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c129",
    text: "Kata slang",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c130",
    text: "Singkatan chat",
    lang: "ID",
    code: "E",
    chaos: "Yang telat, tarik napas panjang!",
    enabled: true,
  },
  {
    id: "c131",
    text: "Cara bilang iya",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c132",
    text: "Cara bilang nggak",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c133",
    text: "Jawaban aman saat bingung",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c134",
    text: "Kalimat teman receh",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c135",
    text: "Panggilan teman",
    lang: "ID",
    code: "G",
    chaos: "Semua bilang \"Cieee\" bareng!",
    enabled: true,
  },
  {
    id: "c136",
    text: "Alasan batal pergi",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  {
    id: "c137",
    text: "Alasan bangun kesiangan",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c138",
    text: "Alasan baterai habis",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c139",
    text: "Aktivitas saat Wi-Fi mati",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c140",
    text: "Random thought yang harmless",
    lang: "MIX",
    code: "A",
    chaos: "Jawab sambil melet lidah!",
    enabled: true,
  },
  {
    id: "c141",
    text: "Negara",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c142",
    text: "Kota",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c143",
    text: "Planet",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c144",
    text: "Dinosaurus",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c145",
    text: "Jenis pohon",
    lang: "ID",
    code: "B",
    chaos: "Yang salah jawab, jentikkan jari!",
    enabled: true,
  },
  {
    id: "c146",
    text: "Bunga",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c147",
    text: "Alat musik",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c148",
    text: "Pekerjaan",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c149",
    text: "Bahasa",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c150",
    text: "Tanda baca",
    lang: "ID",
    code: "D",
    chaos: "Semua wajib senyum lebar dulu!",
    enabled: true,
  },
  {
    id: "c151",
    text: "Alasan belum bales chat",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c152",
    text: "Intronya lagu Indonesia pop",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c153",
    text: "Screenshot yang tak dibaca",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c154",
    text: "Gaya jalan pas kepleset",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c155",
    text: "Mimpi buruk waktu kecil",
    lang: "ID",
    code: "E",
    chaos: "Jawaban pakai nada nyanyi!",
    enabled: true,
  },
  {
    id: "c156",
    text: "Barang checkout ongkir gratis",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c157",
    text: "Kalimat pas nyenggol tiang",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c158",
    text: "Suara misterius tengah malam",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c159",
    text: "Cita-cita random pas TK",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c160",
    text: "Aktivitas pas pura-pura sibuk",
    lang: "ID",
    code: "G",
    chaos: "Yang menang, kedip mata bangga!",
    enabled: true,
  },
  {
    id: "c161",
    text: "Topik pembicaraan bapak-bapak ronda",
    lang: "ID",
    code: "D",
    enabled: true,
  },
  {
    id: "c162",
    text: "Reaksi salah masuk toilet",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c163",
    text: "Cemilan cepat habis nonton",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c164",
    text: "Momen konyol mati lampu",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c165",
    text: "Alasan pura-pura tidur angkot",
    lang: "ID",
    code: "A",
    chaos: "Semua tos pakai siku!",
    enabled: true,
  },
  {
    id: "c166",
    text: "Versi daerah kata 'Sip'",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c167",
    text: "Hal dicari saat kondangan",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c168",
    text: "Gaya foto anak kuliahan",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c169",
    text: "Mitos takut mandi malam",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c170",
    text: "Kebiasaan buruk saat mandi",
    lang: "ID",
    code: "B",
    chaos: "Jawab sambil goyang kepala!",
    enabled: true,
  },
  {
    id: "c171",
    text: "Reaksi pas dompet ketinggalan",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c172",
    text: "Hewan bersuara mirip instrumen",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c173",
    text: "Benda buat ganjel pintu",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c174",
    text: "Kombinasi makanan aneh enak",
    lang: "MIX",
    code: "G",
    enabled: true,
  },
  {
    id: "c175",
    text: "Alasan batalin rencana wacana",
    lang: "ID",
    code: "D",
    chaos: "Yang telat jawab, tepuk meja!",
    enabled: true,
  },
  {
    id: "c176",
    text: "Lagu berasa klip musik",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c177",
    text: "Penyesalan abis potong rambut",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c178",
    text: "Eksperimen aneh waktu SD",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c179",
    text: "Belanja pertama menang lotre",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c180",
    text: "Gaya mengetik WhatsApp ngeselin",
    lang: "MIX",
    code: "F",
    chaos: "Semua teriak nama sendiri dulu!",
    enabled: true,
  },
  {
    id: "c181",
    text: "Sound TikTok nempel otak",
    lang: "MIX",
    code: "C",
    enabled: true,
  },
  {
    id: "c182",
    text: "Alasan senyum sendiri jalan",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c183",
    text: "Barang unik di dashboard",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c184",
    text: "Superpower konyol tapi berguna",
    lang: "MIX",
    code: "B",
    enabled: true,
  },
  {
    id: "c185",
    text: "Jawaban pas ditanya nikah",
    lang: "ID",
    code: "G",
    chaos: "Jawaban wajib pelan-pelan misterius!",
    enabled: true,
  },
  {
    id: "c186",
    text: "Camilan wajib pas nge-game",
    lang: "MIX",
    code: "E",
    enabled: true,
  },
  {
    id: "c187",
    text: "Aktivitas menunggu antrean panjang",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c188",
    text: "Hal dilakukan sendirian rumah",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c189",
    text: "Stiker WA saat sepi",
    lang: "MIX",
    code: "D",
    enabled: true,
  },
  {
    id: "c190",
    text: "Alasan ganti foto profil",
    lang: "ID",
    code: "A",
    chaos: "Yang salah jawab, jongkok sebentar!",
    enabled: true,
  },
  {
    id: "c191",
    text: "Hal bikin merasa dewasa",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c192",
    text: "Drama sepele bikin heboh",
    lang: "ID",
    code: "C",
    enabled: true,
  },
  {
    id: "c193",
    text: "Benda jatuh bunyinya kenceng",
    lang: "ID",
    code: "A",
    enabled: true,
  },
  {
    id: "c194",
    text: "Gaya jalan saat kepanasan",
    lang: "ID",
    code: "F",
    enabled: true,
  },
  {
    id: "c195",
    text: "Momen awkward sama ojol",
    lang: "MIX",
    code: "C",
    chaos: "Semua pemain saling pandang dulu!",
    enabled: true,
  },
  {
    id: "c196",
    text: "Barang hilang tiba-tiba muncul",
    lang: "ID",
    code: "H",
    enabled: true,
  },
  {
    id: "c197",
    text: "Pura-pura ngerti padahal bingung",
    lang: "ID",
    code: "E",
    enabled: true,
  },
  {
    id: "c198",
    text: "Cara atasi obrolan garing",
    lang: "ID",
    code: "B",
    enabled: true,
  },
  {
    id: "c199",
    text: "Kejadian konyol resep baru",
    lang: "ID",
    code: "G",
    enabled: true,
  },
  {
    id: "c200",
    text: "Aksi sepele berasa pahlawan",
    lang: "ID",
    code: "D",
    chaos: "Jawab sambil angkat alis!",
    enabled: true,
  },
  // Tambahan 100 kartu Anomia: c201-c300
// Tempelkan blok ini sebelum `];` pada window.SEED_CARDS.

// ===== Tema 1: Nusantara =====
{
  id: "c201",
  text: "Makanan khas Indonesia",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c202",
  text: "Kota wisata di Indonesia",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c203",
  text: "Pulau di Indonesia",
  lang: "ID",
  code: "A",
  enabled: true,
},
{
  id: "c204",
  text: "Tarian tradisional Indonesia",
  lang: "ID",
  code: "C",
  enabled: true,
},
{
  id: "c205",
  text: "Alat musik tradisional Indonesia",
  lang: "ID",
  code: "D",
  chaos: "Yang menang, sorak paling keras!",
  enabled: true,
},
{
  id: "c206",
  text: "Bahasa daerah Indonesia",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c207",
  text: "Oleh-oleh khas daerah",
  lang: "ID",
  code: "F",
  enabled: true,
},
{
  id: "c208",
  text: "Tempat wisata alam Indonesia",
  lang: "ID",
  code: "G",
  enabled: true,
},
{
  id: "c209",
  text: "Tokoh legenda Nusantara",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c210",
  text: "Permainan tradisional Indonesia",
  lang: "ID",
  code: "B",
  chaos: "Semua bilang \"Sip!\" bareng!",
  enabled: true,
},

// ===== Tema 2: Travel =====
{
  id: "c211",
  text: "Barang wajib di koper",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c212",
  text: "Aktivitas di bandara",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c213",
  text: "Tempat di dalam bandara",
  lang: "ID",
  code: "A",
  enabled: true,
},
{
  id: "c214",
  text: "Destinasi liburan luar negeri",
  lang: "ID",
  code: "B",
  enabled: true,
},
{
  id: "c215",
  text: "Aktivitas di pantai",
  lang: "ID",
  code: "D",
  chaos: "Jawaban wajib pakai gaya bos!",
  enabled: true,
},
{
  id: "c216",
  text: "Perlengkapan camping",
  lang: "MIX",
  code: "H",
  enabled: true,
},
{
  id: "c217",
  text: "Landmark dunia terkenal",
  lang: "MIX",
  code: "C",
  enabled: true,
},
{
  id: "c218",
  text: "Barang beli buat suvenir",
  lang: "ID",
  code: "E",
  enabled: true,
},
{
  id: "c219",
  text: "Masalah kecil saat traveling",
  lang: "MIX",
  code: "F",
  enabled: true,
},
{
  id: "c220",
  text: "Alasan koper jadi overweight",
  lang: "MIX",
  code: "E",
  chaos: "Yang telat jawab, kedip cepat!",
  enabled: true,
},

// ===== Tema 3: Film & TV =====
{
  id: "c221",
  text: "Genre film",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c222",
  text: "Judul film horor",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c223",
  text: "Karakter film terkenal",
  lang: "ID",
  code: "A",
  enabled: true,
},
{
  id: "c224",
  text: "Film yang punya sekuel",
  lang: "ID",
  code: "C",
  enabled: true,
},
{
  id: "c225",
  text: "Aktor Indonesia",
  lang: "ID",
  code: "D",
  chaos: "Semua tos pakai kaki!",
  enabled: true,
},
{
  id: "c226",
  text: "Aktris Indonesia",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c227",
  text: "Profesi balik layar film",
  lang: "ID",
  code: "F",
  enabled: true,
},
{
  id: "c228",
  text: "Benda di dalam bioskop",
  lang: "ID",
  code: "G",
  enabled: true,
},
{
  id: "c229",
  text: "Acara TV kompetisi",
  lang: "ID",
  code: "A",
  enabled: true,
},
{
  id: "c230",
  text: "Film bertema luar angkasa",
  lang: "ID",
  code: "G",
  chaos: "Jawab sambil tunjuk sesama pemain!",
  enabled: true,
},

// ===== Tema 4: Gaming =====
{
  id: "c231",
  text: "Genre game",
  lang: "MIX",
  code: "D",
  enabled: true,
},
{
  id: "c232",
  text: "Karakter video game",
  lang: "MIX",
  code: "H",
  enabled: true,
},
{
  id: "c233",
  text: "Item dalam game",
  lang: "MIX",
  code: "A",
  enabled: true,
},
{
  id: "c234",
  text: "Musuh dalam game",
  lang: "MIX",
  code: "B",
  enabled: true,
},
{
  id: "c235",
  text: "Game multiplayer",
  lang: "MIX",
  code: "D",
  chaos: "Yang salah jawab, garuk kepala!",
  enabled: true,
},
{
  id: "c236",
  text: "Hal bikin rage quit",
  lang: "MIX",
  code: "H",
  enabled: true,
},
{
  id: "c237",
  text: "Perangkat gaming",
  lang: "MIX",
  code: "C",
  enabled: true,
},
{
  id: "c238",
  text: "Tombol keyboard buat gaming",
  lang: "MIX",
  code: "E",
  enabled: true,
},
{
  id: "c239",
  text: "Hadiah dalam game",
  lang: "MIX",
  code: "F",
  enabled: true,
},
{
  id: "c240",
  text: "Lokasi umum dalam game",
  lang: "MIX",
  code: "G",
  chaos: "Semua wajib bilang \"Wah!\" dulu!",
  enabled: true,
},

// ===== Tema 5: Olahraga =====
{
  id: "c241",
  text: "Cabang olahraga Olimpiade",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c242",
  text: "Posisi pemain sepak bola",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c243",
  text: "Peralatan olahraga",
  lang: "ID",
  code: "A",
  enabled: true,
},
{
  id: "c244",
  text: "Klub sepak bola",
  lang: "ID",
  code: "C",
  enabled: true,
},
{
  id: "c245",
  text: "Gerakan olahraga",
  lang: "ID",
  code: "D",
  chaos: "Jawaban pakai suara berat!",
  enabled: true,
},
{
  id: "c246",
  text: "Olahraga air",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c247",
  text: "Olahraga raket",
  lang: "ID",
  code: "F",
  enabled: true,
},
{
  id: "c248",
  text: "Benda di stadion",
  lang: "ID",
  code: "G",
  enabled: true,
},
{
  id: "c249",
  text: "Istilah sepak bola",
  lang: "ID",
  code: "B",
  enabled: true,
},
{
  id: "c250",
  text: "Alasan wasit menghentikan pertandingan",
  lang: "ID",
  code: "H",
  chaos: "Yang menang, angkat kedua tangan!",
  enabled: true,
},

// ===== Tema 6: Sains & Alam =====
{
  id: "c251",
  text: "Alat di laboratorium",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c252",
  text: "Hewan laut",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c253",
  text: "Fenomena alam",
  lang: "ID",
  code: "A",
  enabled: true,
},
{
  id: "c254",
  text: "Bagian tubuh manusia",
  lang: "ID",
  code: "B",
  enabled: true,
},
{
  id: "c255",
  text: "Organ tubuh manusia",
  lang: "ID",
  code: "D",
  chaos: "Semua pemain hitung mundur dulu!",
  enabled: true,
},
{
  id: "c256",
  text: "Unsur kimia",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c257",
  text: "Sumber energi",
  lang: "ID",
  code: "C",
  enabled: true,
},
{
  id: "c258",
  text: "Benda yang bisa mengapung",
  lang: "ID",
  code: "E",
  enabled: true,
},
{
  id: "c259",
  text: "Hewan nokturnal",
  lang: "ID",
  code: "F",
  enabled: true,
},
{
  id: "c260",
  text: "Benda di luar angkasa",
  lang: "ID",
  code: "D",
  chaos: "Jawab sambil pura-pura mikir keras!",
  enabled: true,
},

// ===== Tema 7: Kantor & Kerja =====
{
  id: "c261",
  text: "Jabatan di kantor",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c262",
  text: "Alasan meeting molor",
  lang: "MIX",
  code: "H",
  enabled: true,
},
{
  id: "c263",
  text: "Barang di meja kantor",
  lang: "ID",
  code: "A",
  enabled: true,
},
{
  id: "c264",
  text: "Aplikasi untuk kerja",
  lang: "ID",
  code: "C",
  enabled: true,
},
{
  id: "c265",
  text: "Kalimat sering muncul meeting",
  lang: "MIX",
  code: "D",
  chaos: "Yang telat jawab, tarik kursi!",
  enabled: true,
},
{
  id: "c266",
  text: "Barang di pantry kantor",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c267",
  text: "Profesi yang memakai seragam",
  lang: "ID",
  code: "F",
  enabled: true,
},
{
  id: "c268",
  text: "Aktivitas makan siang kantor",
  lang: "ID",
  code: "G",
  enabled: true,
},
{
  id: "c269",
  text: "Alasan izin bolos kerja",
  lang: "ID",
  code: "E",
  enabled: true,
},
{
  id: "c270",
  text: "File sering dicari laptop",
  lang: "ID",
  code: "H",
  chaos: "Semua bilang \"Gaskeun!\" bareng!",
  enabled: true,
},

// ===== Tema 8: Sosial & Tongkrongan =====
{
  id: "c271",
  text: "Topik first date",
  lang: "MIX",
  code: "D",
  enabled: true,
},
{
  id: "c272",
  text: "Hadiah ulang tahun",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c273",
  text: "Aktivitas saat reuni",
  lang: "ID",
  code: "A",
  enabled: true,
},
{
  id: "c274",
  text: "Tipe teman di tongkrongan",
  lang: "ID",
  code: "B",
  enabled: true,
},
{
  id: "c275",
  text: "Acara keluarga",
  lang: "ID",
  code: "D",
  chaos: "Jawaban wajib pakai gaya berita!",
  enabled: true,
},
{
  id: "c276",
  text: "Kalimat setelah salah kirim",
  lang: "MIX",
  code: "H",
  enabled: true,
},
{
  id: "c277",
  text: "Bawaan main rumah teman",
  lang: "ID",
  code: "C",
  enabled: true,
},
{
  id: "c278",
  text: "Alasan pulang duluan nongkrong",
  lang: "ID",
  code: "E",
  enabled: true,
},
{
  id: "c279",
  text: "Pemicu grup chat ramai",
  lang: "MIX",
  code: "F",
  enabled: true,
},
{
  id: "c280",
  text: "Aktivitas nongkrong tanpa HP",
  lang: "MIX",
  code: "G",
  chaos: "Yang salah jawab, tepuk paha!",
  enabled: true,
},

// ===== Tema 9: Horor & Misteri =====
{
  id: "c281",
  text: "Makhluk horor",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c282",
  text: "Tempat menyeramkan",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c283",
  text: "Benda di rumah kosong",
  lang: "ID",
  code: "A",
  enabled: true,
},
{
  id: "c284",
  text: "Suara khas film horor",
  lang: "ID",
  code: "C",
  enabled: true,
},
{
  id: "c285",
  text: "Kejadian aneh rumah malam",
  lang: "ID",
  code: "D",
  chaos: "Semua tos pakai punggung tangan!",
  enabled: true,
},
{
  id: "c286",
  text: "Benda buat lawan monster",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c287",
  text: "Kesalahan klasik film horor",
  lang: "ID",
  code: "F",
  enabled: true,
},
{
  id: "c288",
  text: "Kostum Halloween",
  lang: "MIX",
  code: "G",
  enabled: true,
},
{
  id: "c289",
  text: "Urban legend",
  lang: "MIX",
  code: "B",
  enabled: true,
},
{
  id: "c290",
  text: "Cara kabur dari zombie",
  lang: "ID",
  code: "D",
  chaos: "Jawab sambil tutup satu mata!",
  enabled: true,
},

// ===== Tema 10: Masa Depan & Fantasi =====
{
  id: "c291",
  text: "Planet fiksi",
  lang: "ID",
  code: "D",
  enabled: true,
},
{
  id: "c292",
  text: "Pekerjaan masa depan",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c293",
  text: "Gadget masa depan",
  lang: "MIX",
  code: "A",
  enabled: true,
},
{
  id: "c294",
  text: "Kekuatan super",
  lang: "ID",
  code: "B",
  enabled: true,
},
{
  id: "c295",
  text: "Kendaraan futuristik",
  lang: "ID",
  code: "D",
  chaos: "Yang menang, teriak nama kartu!",
  enabled: true,
},
{
  id: "c296",
  text: "Benda dalam pesawat antariksa",
  lang: "ID",
  code: "H",
  enabled: true,
},
{
  id: "c297",
  text: "Nama robot fiksi",
  lang: "MIX",
  code: "C",
  enabled: true,
},
{
  id: "c298",
  text: "Alasan alien datang Bumi",
  lang: "ID",
  code: "E",
  enabled: true,
},
{
  id: "c299",
  text: "Barang dibawa ke Mars",
  lang: "ID",
  code: "F",
  enabled: true,
},
{
  id: "c300",
  text: "Benda terlarang mesin waktu",
  lang: "ID",
  code: "E",
  chaos: "Semua wajib bilang \"Mantap!\" dulu!",
  enabled: true,
}
];
