(function(root){
const heights=[4,4,3,3,2,2], colors=['#3CB4E6','#F05696','#32B18E','#FF8040'];
function create(names){if(!Array.isArray(names)||names.length<2||names.length>4)throw Error('Pilih 2–4 pemain');return {players:names.map((name,i)=>({name:String(name).trim().slice(0,24)||`Pemain ${i+1}`,color:colors[i],pos:Array(6).fill(0),tokens:Array(6).fill(0),bonus:[]})),supply:[12,11,10,9,8,7].map(n=>n-(4-names.length)),bonuses:[15,12,9,6],active:0,round:1,actions:[],finalRound:false,over:false,log:['Pendakian dimulai. Lempar empat dadu!']};}
function score(p){return p.tokens.reduce((s,n,i)=>s+n*(i+5),0)+p.bonus.reduce((a,b)=>a+b,0)}
function move(s,n){if(s.over)throw Error('Permainan selesai');if(!Number.isInteger(n)||n<5||n>10)throw Error('Gunung harus 5–10');if(s.actions.length>=4)throw Error('Maksimal empat kelompok dadu per giliran');const i=n-5,p=s.players[s.active];p.pos[i]=Math.min(heights[i],p.pos[i]+1);let msg=`${p.name} naik di gunung ${n}.`;if(p.pos[i]===heights[i]){const other=s.players.find((q,j)=>j!==s.active&&q.pos[i]===heights[i]);if(other){other.pos[i]=0;msg=`${p.name} merebut puncak ${n}! ${other.name} kembali ke kaki gunung.`;}if(s.supply[i]>0){s.supply[i]--;p.tokens[i]++;msg+=` +${n} poin.`;}else msg+=' Token gunung sudah habis.';const sets=Math.min(...p.tokens);while(p.bonus.length<sets&&s.bonuses.length){const b=s.bonuses.shift();p.bonus.push(b);msg+=` Bonus set +${b}!`;}}s.actions.push(n);s.finalRound ||= s.bonuses.length===0||s.supply.filter(n=>n===0).length>=3;s.log.unshift(msg);s.log=s.log.slice(0,40);return s;}
function next(s){if(s.over)throw Error('Permainan selesai');if(s.active===s.players.length-1){if(s.finalRound){s.over=true;s.log.unshift('Permainan selesai. Semua pemain mendapat jumlah giliran yang sama.');return s;}s.round++;}s.active=(s.active+1)%s.players.length;s.actions=[];return s;}
function rank(s){const tops=p=>p.pos.filter((n,i)=>n===heights[i]).length,high=p=>Math.max(0,...p.pos.map((n,i)=>n===heights[i]?i+5:0));return s.players.map((p,i)=>({...p,index:i,score:score(p),tops:tops(p),high:high(p)})).sort((a,b)=>b.score-a.score||b.tops-a.tops||b.high-a.high);}
root.MG={heights,colors,create,score,move,next,rank};if(typeof module!=='undefined')module.exports=root.MG;
})(globalThis);
