const STORAGE_KEY='miau-ngomong-apa-v1';const $=s=>document.querySelector(s);
const E={card:$('#card'),cardContent:$('#cardContent'),progressText:$('#progressText'),categoryText:$('#categoryText'),difficultyText:$('#difficultyText'),flipBtn:$('#flipBtn'),nextBtn:$('#nextBtn'),shuffleBtn:$('#shuffleBtn'),themeBtn:$('#themeBtn'),soundBtn:$('#soundBtn'),manageBtn:$('#manageBtn'),manageDialog:$('#manageDialog'),searchInput:$('#searchInput'),cardList:$('#cardList'),addBtn:$('#addBtn'),exportBtn:$('#exportBtn'),importInput:$('#importInput'),resetBtn:$('#resetBtn'),formDialog:$('#formDialog'),cardForm:$('#cardForm'),formEyebrow:$('#formEyebrow'),formTitle:$('#formTitle'),formCloseBtn:$('#formCloseBtn'),cancelBtn:$('#cancelBtn'),toast:$('#toast')};
let db=load(),deck=[],deckIndex=0,revealed=false,editingId=null,audioCtx=null;
function clone(v){return JSON.parse(JSON.stringify(v))}function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(m){E.toast.textContent=m;E.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.classList.remove('show'),1600)}
function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY));if(Array.isArray(x?.cards))return x}catch{}return{cards:clone(SEED_CARDS),theme:'light',sound:true,nextSeq:151}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(db))}function theme(){document.documentElement.dataset.theme=db.theme;E.themeBtn.textContent=db.theme==='dark'?'☀️':'🌙';E.soundBtn.textContent=db.sound?'🔊':'🔇'}
function beep(f=600,d=.06){if(!db.sound)return;try{audioCtx||=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=f;g.gain.setValueAtTime(.05,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch{}}
function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}function build(){deck=shuffle(db.cards.map(c=>c.id));deckIndex=0;revealed=false}
function current(){if(!deck.length)build();return db.cards.find(c=>c.id===deck[deckIndex])||db.cards[0]}function anim(){E.card.classList.add('flip-out');setTimeout(()=>{render();E.card.classList.remove('flip-out');E.card.classList.add('flip-in');setTimeout(()=>E.card.classList.remove('flip-in'),190)},170)}
function render(){const c=current();if(!c){E.cardContent.innerHTML='<div class="empty">Tidak ada kartu.</div>';return}E.progressText.textContent=`${deckIndex+1} / ${deck.length}`;E.categoryText.textContent=c.category;E.difficultyText.textContent=c.difficulty;
E.cardContent.innerHTML=!revealed?`<div class="card-inner"><div class="card-id">${esc(c.id)} • ${esc(c.category)}</div><div class="prompt">${esc(c.gibberish)}</div><p class="instruction">Baca keras beberapa kali. Dengarkan bunyinya, jangan artikan tulisannya.</p></div>`:`<div class="card-inner"><div class="card-id">JAWABAN • ${esc(c.id)}</div><div class="prompt" style="font-size:clamp(22px,5vw,42px);color:var(--muted)">${esc(c.gibberish)}</div><hr class="reveal-rule"><div class="answer-label">JAWABAN ASLI</div><div class="answer">${esc(c.answer)}</div></div>`;E.flipBtn.textContent=revealed?'🙈 SEMBUNYIKAN JAWABAN':'🔄 BALIK KARTU'}
function flip(){revealed=!revealed;beep(revealed?820:500,.07);anim()}function next(){deckIndex++;if(deckIndex>=deck.length){deck=shuffle(db.cards.map(c=>c.id));deckIndex=0;toast('Deck selesai — dikocok ulang!')}revealed=false;beep(620);anim()}function reshuffle(){build();beep(900,.08);toast('Deck dikocok ulang.');anim()}
function list(q=''){q=q.toLowerCase().trim();const a=db.cards.filter(c=>(`${c.id} ${c.gibberish} ${c.answer} ${c.category} ${c.difficulty}`).toLowerCase().includes(q));E.cardList.innerHTML=a.map(c=>`<div class="crud-row"><div><div class="crud-title">${esc(c.id)} • ${esc(c.answer)}</div><div class="crud-meta">${esc(c.gibberish)} • ${esc(c.category)} • ${esc(c.difficulty)}</div></div><div class="crud-actions"><button data-e="${c.id}">✏️</button><button data-d="${c.id}">🗑️</button></div></div>`).join('')||'<div class="empty">Tidak ada hasil.</div>';document.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>form(b.dataset.e));document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>del(b.dataset.d))}
function form(id=null){editingId=id;const c=id?db.cards.find(x=>x.id===id):null;E.formEyebrow.textContent=c?c.id:'KARTU BARU';E.formTitle.textContent=c?'Edit Kartu':'Tambah Kartu';const f=E.cardForm.elements;f.gibberish.value=c?.gibberish||'';f.answer.value=c?.answer||'';f.category.value=c?.category||'Random';f.difficulty.value=c?.difficulty||'Sedang';E.formDialog.showModal()}
function del(id){const c=db.cards.find(x=>x.id===id);if(!c||!confirm(`Hapus ${id} — ${c.answer}?`))return;db.cards=db.cards.filter(x=>x.id!==id);save();build();render();list(E.searchInput.value);toast(`${id} dihapus.`)}
E.cardForm.onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),x={gibberish:String(f.get('gibberish')).trim(),answer:String(f.get('answer')).trim(),category:String(f.get('category')).trim()||'Random',difficulty:String(f.get('difficulty'))};if(editingId)Object.assign(db.cards.find(c=>c.id===editingId),x);else db.cards.push({id:`G${String(db.nextSeq++).padStart(3,'0')}`,...x});save();build();render();list(E.searchInput.value);E.formDialog.close();beep(760);toast('Kartu disimpan.')}
function exp(){const b=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='miau-ngomong-apa.json';a.click();URL.revokeObjectURL(a.href)}
async function imp(e){try{const x=JSON.parse(await e.target.files[0].text());if(!Array.isArray(x.cards)||!x.cards.every(c=>c.id&&c.gibberish&&c.answer))throw 0;db=x;db.theme||='light';db.sound??=true;db.nextSeq||=Math.max(0,...db.cards.map(c=>Number(String(c.id).replace(/\D/g,''))||0))+1;save();theme();build();render();list();toast('Import berhasil.')}catch{toast('JSON tidak valid.')}e.target.value=''}
function reset(){if(!confirm('Reset ke 150 kartu bawaan?'))return;db.cards=clone(SEED_CARDS);db.nextSeq=151;save();build();render();list();toast('150 seed dipulihkan.')}
E.flipBtn.onclick=flip;E.card.onclick=flip;E.nextBtn.onclick=next;E.shuffleBtn.onclick=reshuffle;E.manageBtn.onclick=()=>{E.searchInput.value='';list();E.manageDialog.showModal()};E.searchInput.oninput=e=>list(e.target.value);E.addBtn.onclick=()=>form();E.formCloseBtn.onclick=E.cancelBtn.onclick=()=>E.formDialog.close();E.exportBtn.onclick=exp;E.importInput.onchange=imp;E.resetBtn.onclick=reset;E.themeBtn.onclick=()=>{db.theme=db.theme==='dark'?'light':'dark';save();theme()};E.soundBtn.onclick=()=>{db.sound=!db.sound;save();theme();beep(700)};
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();flip()}if(e.key==='ArrowRight'){e.preventDefault();next()}});theme();build();render();