const KEY="spectrum-party-genz-wavelength-v2";
let state=load(),editing=null,current=null,gameCardId=null;
let game={phase:"psychic",target:-90,needle:-90,dragging:false};
const $=s=>document.querySelector(s);
function load(){let raw=localStorage.getItem(KEY);if(!raw)return{cards:structuredClone(STARTER_CARDS),bag:[],drawn:[],light:false};try{let x=JSON.parse(raw);return{cards:Array.isArray(x.cards)?x.cards:structuredClone(STARTER_CARDS),bag:Array.isArray(x.bag)?x.bag:[],drawn:Array.isArray(x.drawn)?x.drawn:[],light:!!x.light}}catch{return{cards:structuredClone(STARTER_CARDS),bag:[],drawn:[],light:false}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(v=""){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function byId(id){return state.cards.find(c=>c.id===id)}
function markup(c,n,klass=""){return `<article class="card ${klass}" data-id="${c.id}" style="--left:${c.leftColor||"#ef4444"};--right:${c.rightColor||"#3b82f6"}"><div class="cardglow"></div><div class="cardtop"><span class="chip">${esc((c.category||"Lainnya").toUpperCase())}</span><span class="num">#${String(n).padStart(3,"0")}</span></div><div class="spectrum"><div class="pole"><span class="arrow">←</span><strong>${esc(c.left)}</strong></div><div class="vs"><span></span><b>VS</b><span></span></div><div class="pole right"><strong>${esc(c.right)}</strong><span class="arrow">→</span></div></div><div class="bar"><i></i></div><div class="foot">WHERE DOES YOUR CLUE LAND?</div></article>`}
function shuffle(){let a=state.cards.map(c=>c.id);for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}state.bag=a;state.drawn=[]}
function clean(){let ok=new Set(state.cards.map(c=>c.id));state.bag=state.bag.filter(id=>ok.has(id));state.drawn=state.drawn.filter(id=>ok.has(id));if(!state.bag.length&&state.cards.length)shuffle()}
function cats(){let s=$("#categoryFilter"),old=s.value,arr=[...new Set(state.cards.map(c=>c.category||"Lainnya"))].sort((a,b)=>a.localeCompare(b,"id"));s.innerHTML='<option value="">Semua kategori</option>'+arr.map(x=>`<option>${esc(x)}</option>`).join("");if(arr.includes(old))s.value=old}
function filtered(){let q=$("#searchInput").value.toLowerCase(),cat=$("#categoryFilter").value,a=state.cards.filter(c=>(!q||`${c.left} ${c.right} ${c.category}`.toLowerCase().includes(q))&&(!cat||c.category===cat));let sort=$("#sortSelect").value;if(sort==="az")a.sort((x,y)=>x.left.localeCompare(y.left,"id"));if(sort==="category")a.sort((x,y)=>(x.category||"").localeCompare(y.category||"","id")||x.left.localeCompare(y.left,"id"));return a}
function renderLib(){cats();let a=filtered();$("#resultCount").textContent=`${a.length} kartu`;$("#grid").innerHTML=a.length?a.map(c=>markup(c,state.cards.findIndex(x=>x.id===c.id)+1)).join(""):'<div class="empty">Tidak ada kartu yang cocok.</div>'}
function status(){clean();$("#remainingCount").textContent=state.bag.length}
function draw(){if(!state.cards.length)return alert("Card Library kosong.");clean();if(!state.bag.length)shuffle();let id=state.bag.pop();state.drawn.push(id);current=id;let c=byId(id),n=state.cards.findIndex(x=>x.id===id)+1;$("#placeholder").classList.add("hidden");$("#randomHost").classList.remove("hidden");$("#returnBtn").classList.remove("hidden");$("#playRandomBtn").classList.remove("hidden");$("#randomHost").innerHTML=markup(c,n,"random");$("#randomBtn").textContent="🎲 NEXT RANDOM";status();save()}
function giveBack(){if(!current)return;if(!state.bag.includes(current))state.bag.push(current);state.drawn=state.drawn.filter(x=>x!==current);current=null;$("#randomHost").classList.add("hidden");$("#randomHost").innerHTML="";$("#placeholder").classList.remove("hidden");$("#returnBtn").classList.add("hidden");$("#playRandomBtn").classList.add("hidden");$("#randomBtn").textContent="🎲 RANDOM CARD";status();save()}
function preview(){let c={id:"preview",left:$("#leftInput").value||"Ujung kiri",right:$("#rightInput").value||"Ujung kanan",category:$("#categoryInput").value||"Kategori",leftColor:$("#leftColorInput").value,rightColor:$("#rightColorInput").value};$("#preview").innerHTML=markup(c,editing?state.cards.findIndex(x=>x.id===editing)+1:state.cards.length+1)}
function openEdit(id=null){editing=id;let c=id?byId(id):{left:"",right:"",category:"Internet",leftColor:"#ef4444",rightColor:"#3b82f6"};$("#dialogTitle").textContent=id?"Edit Kartu":"Buat Kartu";$("#leftInput").value=c.left;$("#rightInput").value=c.right;$("#categoryInput").value=c.category||"";$("#leftColorInput").value=c.leftColor||"#ef4444";$("#rightColorInput").value=c.rightColor||"#3b82f6";$("#deleteBtn").classList.toggle("hidden",!id);$("#playCardBtn").classList.toggle("hidden",!id);preview();$("#editor").showModal()}
function closeEditor(){if($("#editor").open)$("#editor").close()}
$("#cardForm").onsubmit=e=>{e.preventDefault();let p={left:$("#leftInput").value.trim(),right:$("#rightInput").value.trim(),category:$("#categoryInput").value.trim()||"Lainnya",leftColor:$("#leftColorInput").value,rightColor:$("#rightColorInput").value};if(!p.left||!p.right)return;if(editing)Object.assign(byId(editing),p);else{let id=crypto.randomUUID();state.cards.push({id,...p});state.bag.push(id)}editing=null;closeEditor();renderLib();status();save()}
$("#deleteBtn").onclick=()=>{let c=byId(editing);if(!c||!confirm(`Hapus "${c.left} ↔ ${c.right}"?`))return;state.cards=state.cards.filter(x=>x.id!==editing);state.bag=state.bag.filter(x=>x!==editing);state.drawn=state.drawn.filter(x=>x!==editing);if(current===editing){current=null;$("#randomHost").classList.add("hidden");$("#randomHost").innerHTML="";$("#placeholder").classList.remove("hidden");$("#returnBtn").classList.add("hidden");$("#playRandomBtn").classList.add("hidden");$("#randomBtn").textContent="🎲 RANDOM CARD"}editing=null;closeEditor();renderLib();status();save()}
document.addEventListener("click",e=>{let t=e.target.closest("[data-close],#grid .card");if(!t)return;if(t.hasAttribute("data-close"))return closeEditor();if(t.matches("#grid .card"))openEdit(t.dataset.id)})
for(let id of ["leftInput","rightInput","categoryInput","leftColorInput","rightColorInput"])$("#"+id).addEventListener("input",preview);
$("#randomBtn").onclick=draw;$("#returnBtn").onclick=giveBack;$("#addBtn").onclick=()=>openEdit();$("#searchInput").oninput=renderLib;$("#categoryFilter").onchange=renderLib;$("#sortSelect").onchange=renderLib;
$("#resetBtn").onclick=()=>{if(!confirm("Reset ke 100 kartu bawaan? Semua edit dan kartu buatan akan hilang."))return;state.cards=structuredClone(STARTER_CARDS);state.bag=[];state.drawn=[];current=null;$("#randomHost").classList.add("hidden");$("#randomHost").innerHTML="";$("#placeholder").classList.remove("hidden");$("#returnBtn").classList.add("hidden");$("#playRandomBtn").classList.add("hidden");$("#randomBtn").textContent="🎲 RANDOM CARD";shuffle();renderLib();status();save()}
$("#themeBtn").onclick=()=>{state.light=!state.light;document.body.classList.toggle("light",state.light);save()}

/* ===== WAVELENGTH DIAL ===== */
const SVG_NS="http://www.w3.org/2000/svg";
const CX=400,CY=380,INNER=235,OUTER=326;
const SEGMENTS=[[-28,-16,2,"#f6b21f"],[-16,-7,3,"#fa4b42"],[-7,7,4,"#74b9d4"],[7,16,3,"#fa4b42"],[16,28,2,"#f6b21f"]];
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function polar(r,deg){let a=deg*Math.PI/180;return{x:CX+r*Math.cos(a),y:CY+r*Math.sin(a)}}
function sectorPath(start,end,r1=INNER,r2=OUTER){let a=polar(r2,start),b=polar(r2,end),c=polar(r1,end),d=polar(r1,start);return `M ${a.x} ${a.y} A ${r2} ${r2} 0 0 1 ${b.x} ${b.y} L ${c.x} ${c.y} A ${r1} ${r1} 0 0 0 ${d.x} ${d.y} Z`}
function renderTarget(){let g=$("#targetGroup");g.innerHTML="";for(let [s,e,score,color] of SEGMENTS){let start=game.target+s,end=game.target+e;let p=document.createElementNS(SVG_NS,"path");p.setAttribute("d",sectorPath(start,end));p.setAttribute("fill",color);p.setAttribute("stroke","#f5eddc");p.setAttribute("stroke-width","2");g.appendChild(p);let mid=(start+end)/2,pos=polar((INNER+OUTER)/2,mid),txt=document.createElementNS(SVG_NS,"text");txt.setAttribute("x",pos.x);txt.setAttribute("y",pos.y+7);txt.setAttribute("text-anchor","middle");txt.setAttribute("class","target-score");txt.textContent=score;g.appendChild(txt)}}
function renderNeedle(){let end=polar(325,game.needle),handle=polar(342,game.needle);$("#needleLine").setAttribute("x2",end.x);$("#needleLine").setAttribute("y2",end.y);$("#needleHandle").setAttribute("cx",handle.x);$("#needleHandle").setAttribute("cy",handle.y)}
function renderGame(){renderTarget();renderNeedle();let dlg=$("#wavelengthDialog");dlg.classList.toggle("target-hidden",game.phase==="guess");$("#randomTargetBtn").classList.toggle("hidden",game.phase!=="psychic");$("#hideTargetBtn").classList.toggle("hidden",game.phase!=="psychic");$("#revealTargetBtn").classList.toggle("hidden",game.phase!=="guess");$("#newRoundBtn").classList.toggle("hidden",game.phase!=="result");$("#roundResult").classList.toggle("hidden",game.phase!=="result");if(game.phase==="psychic"){$("#dragHint").textContent="Psychic: geser target berwarna atau tekan Acak Target.";$("#phaseHelp").innerHTML="<b>Psychic saja yang melihat layar.</b> Atur target, pikirkan clue, lalu tutup target."}else if(game.phase==="guess"){$("#dragHint").textContent="Tim penebak: geser jarum merah ke posisi pilihan kalian.";$("#phaseHelp").innerHTML="<b>Target sudah tersembunyi.</b> Diskusikan clue dan tempatkan jarum; Psychic jangan membantu."}else{$("#dragHint").textContent="Hasil ronde sudah dibuka.";$("#phaseHelp").innerHTML="Bandingkan jarum dengan target. Tekan <b>Ronde Baru</b> untuk memakai kartu yang sama lagi."}}
function randomTarget(){game.target=-147+Math.random()*114;game.needle=-90;game.phase="psychic";renderGame()}
function score(){let d=Math.abs(game.needle-game.target);if(d<=7)return 4;if(d<=16)return 3;if(d<=28)return 2;return 0}
function reveal(){game.phase="result";let s=score();$("#scoreValue").textContent=`${s} POIN`;$("#scoreText").textContent=s===4?"Bullseye! Jarum masuk zona tengah.":s===3?"Dekat sekali — masuk zona 3.":s===2?"Masih kena target — zona 2.":"Meleset dari target.";renderGame()}
function openWavelength(id){let c=byId(id);if(!c)return;gameCardId=id;$("#gameCardStrip").innerHTML=`<div class="game-pole" style="background:${c.leftColor||'#ef4444'}"><span class="big-arrow">←</span><span>${esc(c.left)}</span></div><div class="game-pole right-pole" style="background:${c.rightColor||'#3b82f6'}"><span>${esc(c.right)}</span><span class="big-arrow">→</span></div>`;randomTarget();if(!$("#wavelengthDialog").open)$("#wavelengthDialog").showModal()}
function pointerAngle(evt){let svg=$("#dialSvg"),pt=svg.createSVGPoint();pt.x=evt.clientX;pt.y=evt.clientY;let local=pt.matrixTransform(svg.getScreenCTM().inverse());let angle=Math.atan2(local.y-CY,local.x-CX)*180/Math.PI;return clamp(angle,-175,-5)}
function updateFromPointer(evt){let a=pointerAngle(evt);if(game.phase==="psychic")game.target=clamp(a,-147,-33);else if(game.phase==="guess")game.needle=a;else return;renderGame()}
$("#dialSvg").addEventListener("pointerdown",e=>{if(game.phase==="result")return;game.dragging=true;$(".dial-wrap").classList.add("dragging");$("#dialSvg").setPointerCapture(e.pointerId);updateFromPointer(e)});
$("#dialSvg").addEventListener("pointermove",e=>{if(game.dragging)updateFromPointer(e)});
function endDrag(e){game.dragging=false;$(".dial-wrap").classList.remove("dragging");try{$("#dialSvg").releasePointerCapture(e.pointerId)}catch{}}
$("#dialSvg").addEventListener("pointerup",endDrag);$("#dialSvg").addEventListener("pointercancel",endDrag);
$("#dialLeftBtn").onclick=()=>{if(game.phase==="psychic")game.target=clamp(game.target-3,-147,-33);else if(game.phase==="guess")game.needle=clamp(game.needle-3,-175,-5);renderGame()};
$("#dialRightBtn").onclick=()=>{if(game.phase==="psychic")game.target=clamp(game.target+3,-147,-33);else if(game.phase==="guess")game.needle=clamp(game.needle+3,-175,-5);renderGame()};
$("#randomTargetBtn").onclick=randomTarget;
$("#hideTargetBtn").onclick=()=>{game.phase="guess";game.needle=-90;renderGame()};
$("#revealTargetBtn").onclick=reveal;
$("#newRoundBtn").onclick=randomTarget;
$("#closeGameBtn").onclick=()=>$("#wavelengthDialog").close();
$("#playRandomBtn").onclick=()=>{if(current)openWavelength(current)};
$("#playCardBtn").onclick=()=>{let id=editing;if(!id)return;closeEditor();openWavelength(id)};

document.body.classList.toggle("light",state.light);$("#heroDemo").innerHTML=markup(STARTER_CARDS[0],1);clean();renderLib();status();save();
