'use strict';
const $=s=>document.querySelector(s), app=$('#app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const score=(truth,guess)=>30-guess.reduce((s,id,i)=>s+Math.abs(i-truth.indexOf(id)),0);
const validOrder=a=>Array.isArray(a)&&a.length===6&&new Set(a).size===6&&a.every(x=>Number.isInteger(x)&&x>=0&&x<6);
const uid=()=>Array.from(crypto.getRandomValues(new Uint8Array(12)),x=>x.toString(16).padStart(2,'0')).join('');
let state={mode:'single',players:[],round:1,totals:{},answers:[]}, challenge=null, order=[], noticeTimer;
function notify(s){$('#notice').textContent=s;$('#notice').style.display='block';clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').style.display='none',3500)}
function show(html){app.innerHTML=html;window.scrollTo(0,0)}
function btn(id,fn){$('#'+id).onclick=fn}
function steps(n){return '<div class="steps">'+['Kategori','Rahasia A','Tebakan B','Reveal'].map((s,i)=>`<span class="${i===n?'active':''}">${i+1}. ${s}</span>`).join('')}
function guard(fn){try{fn()}catch(e){notify(e.message||'Data tidak valid.')}}
function pack(obj){return 'FK1.'+btoa(Array.from(new TextEncoder().encode(JSON.stringify(obj)),b=>String.fromCharCode(b)).join(''))}
function unpack(s,type){if(s.length>25000||!s.trim().startsWith('FK1.'))throw Error('Kode tidak dikenali. Gunakan kode Favorit Kita.');let o;try{o=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(atob(s.trim().slice(4)),c=>c.charCodeAt(0))))}catch{throw Error('Kode rusak atau belum lengkap.')}if(o.type!==type||typeof o.id!=='string'||o.id.length>60)throw Error('Jenis kode tidak sesuai.');return o}
function download(text,name){const u=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),3000)}
function transfer(code,name){return `<label for="out">Kode untuk dibagikan</label><textarea id="out" class="transfer" readonly>${esc(code)}</textarea><div class="toolbar"><button id="copy">Salin kode</button><button id="save">Unduh berkas</button></div><p class="small">Kirim berkas melalui Bluetooth, AirDrop, USB, atau salin kode lewat sarana yang tersedia. Penerima membuka aplikasi ini di perangkatnya.</p>`}
function wireTransfer(code,name){btn('save',()=>download(code,name));btn('copy',async()=>{try{await navigator.clipboard.writeText(code);notify('Kode disalin')}catch{$('#out').select();notify('Tekan lama teks atau Ctrl+C untuk menyalin.')}})}
function importUI(){return '<label for="incoming">Tempel kode</label><textarea id="incoming" placeholder="FK1.…"></textarea><label for="file">Atau buka berkas permainan</label><input type="file" id="file" accept=".txt,.fk,text/plain">'}
function wireImport(){ $('#file').onchange=async e=>{const f=e.target.files[0];if(f){if(f.size>25000)return notify('Berkas terlalu besar.');$('#incoming').value=await f.text()}} }
function home(){show(`<span class="eyebrow">Seberapa kenal kamu dengan mereka?</span><h1>Enam pilihan.<br><span class="accent">Satu urutan rahasia.</span></h1><p>Pilih cara bermain. Satu orang menjadi A, lainnya menebak sebagai B.</p><div class="grid"><button class="mode" id="single"><span class="badge">SATU PERANGKAT</span><strong>Oper & tebak ↗</strong><small>Giliran rahasia. Cocok untuk satu HP di tengah teman-teman.</small></button><button class="mode" id="multi"><span class="badge">BEBERAPA PERANGKAT</span><strong>Bagi tantangan ↗</strong><small>A membuat tantangan, B mengirim tebakan melalui berkas atau kode.</small></button></div><div class="panel"><details><summary>Cara main & penilaian</summary><p>B memilih kategori. A mengisi enam hal berbeda, dari 0 (paling tidak suka) sampai 5 (paling suka). A memeriksa lalu mengunci urutannya. B menerima pilihan acak dan menyusun tebakan masing-masing. Setelah semua selesai, A membuka hasil.</p><p>Skor = 30 − jumlah selisih peringkat keenam pilihan. Skor tertinggi menang; seri berarti juara bersama. Contoh: dua pilihan tertukar satu posisi menghasilkan 28 poin. Pembalikan total menghasilkan 12 poin.</p><p>Ini variasi tebak urutan sesuai ide Anda, bukan aturan resmi My Favourite Things yang memakai adu kartu dan angka 1 untuk favorit teratas.</p><p>Mode beberapa perangkat tidak memakai room atau sinkronisasi otomatis. Jawaban A tidak dimasukkan ke kode tantangan. Jangan tutup/muat ulang halaman A sebelum ronde selesai. Satu layar memakai pelindung pergantian giliran, bukan sistem anti-curang.</p></details></div>`);btn('single',()=>setup('single'));btn('multi',()=>{show('<h1>Main di perangkat sendiri.</h1><div class="grid"><button class="mode" id="host"><strong>Saya A</strong><small>Buat urutan rahasia dan kumpulkan tebakan.</small></button><button class="mode" id="join"><strong>Saya B</strong><small>Buka tantangan dari A dan kirim jawaban.</small></button></div>');btn('host',()=>setup('multi'));btn('join',join)})}
function setup(mode){state={mode,players:[],round:1,totals:{},answers:[]};show(`<span class="eyebrow">Siapkan meja</span><h1>Siapa yang bermain?</h1><div class="panel"><label for="names">${mode==='single'?'Nama pemain / tim, satu per baris':'Nama A, lalu nama seluruh penebak / tim, satu per baris'}</label><textarea id="names" placeholder="Alya\nBima\nCitra"></textarea><p>2–12 pemain atau tim. Nama pertama menjadi A pada ronde pertama. B lain menebak sendiri-sendiri.</p><button class="primary" id="next">Pilih kategori →</button></div>`);btn('next',()=>{const names=$('#names').value.split('\n').map(x=>x.trim()).filter(Boolean);if(names.length<2||names.length>12||names.some(n=>n.length>30)||new Set(names.map(n=>n.toLowerCase())).size!==names.length)return notify('Isi 2–12 nama berbeda, maksimal 30 karakter per nama.');state.players=names;names.forEach(n=>state.totals[n]=0);category()})}
function category(){state.answers=[];state.a=state.players[(state.round-1)%state.players.length];state.bs=state.players.filter(n=>n!==state.a);show(`${steps(0)}<h1>B, pilih kategori untuk <span class="accent">${esc(state.a)}.</span></h1><div class="toolbar"><span class="badge">RONDE ${state.round}</span><button id="random">⤨ Ambil acak</button></div><div class="grid"><div><label for="search">Cari dari ${CATEGORIES.length} kartu</label><input id="search" placeholder="Misalnya: game, makanan…"></div><div><label for="group">Kelompok kategori</label><select id="group"><option value="">Semua kategori</option>${Object.keys(CATEGORY_GROUPS).map(g=>`<option>${esc(g)}</option>`).join('')}</select></div></div><div class="cards" id="cats"></div><div class="panel"><label for="custom">Atau kategori buatan kalian</label><input id="custom" maxlength="80" placeholder="Tulis kategori sendiri"><button id="use" style="margin-top:12px">Gunakan kategori</button></div>`);const draw=()=>{const list=CATEGORIES.filter(c=>(!$('#group').value||c.group===$('#group').value)&&c.name.toLowerCase().includes($('#search').value.toLowerCase()));$('#cats').innerHTML=list.length?list.map(c=>`<button class="category" data-cat="${esc(c.name)}"><small>${esc(c.group)}</small>${esc(c.name)}</button>`).join(''):'<p>Tidak ditemukan. Coba kata lain atau buat kategori sendiri.</p>';$('#cats').querySelectorAll('button').forEach(b=>b.onclick=()=>choose(b.dataset.cat))};$('#search').oninput=draw;$('#group').onchange=draw;draw();btn('random',()=>{const list=CATEGORIES.filter(c=>!$('#group').value||c.group===$('#group').value);choose(list[Math.floor(Math.random()*list.length)].name)});btn('use',()=>{const v=$('#custom').value.trim();if(v)choose(v);else notify('Tulis kategori terlebih dahulu.')})}
function choose(cat){state.category=cat;shield(state.a,()=>write(), 'Hanya A yang boleh melihat enam pilihan dan urutannya. Pemain lain, lihat ke arah lain.');}
function shield(name,next,message='Serahkan perangkat. Pemain lain tidak boleh melihat tebakan ini.'){show(`<div class="panel center"><div class="lock">▧</div><span class="eyebrow">Giliran rahasia</span><h1>${esc(name)}</h1><p>${esc(message)}</p><button class="primary" id="ready">Saya ${esc(name)}, buka</button></div>`);btn('ready',next)}
function write(values=['','','','','','']){show(`${steps(1)}<span class="eyebrow">RAHASIA ${esc(state.a)}</span><h1>${esc(state.category)}</h1><p>Isi enam pilihan berbeda. Angka 0 paling tidak disukai; angka 5 paling disukai.</p><form id="secret">${values.map((v,i)=>`<label class="rank"><b>${i}</b><input aria-label="Peringkat ${i}" required maxlength="80" value="${esc(v)}" placeholder="${i===0?'Paling tidak suka':i===5?'Paling suka':'Pilihan peringkat '+i}"></label>`).join('')}<button class="primary" type="submit">Periksa urutan →</button></form>`);$('#secret').onsubmit=e=>{e.preventDefault();const vals=[...$('#secret').querySelectorAll('input')].map(i=>i.value.trim());if(vals.some(v=>!v)||new Set(vals.map(v=>v.toLowerCase())).size!==6)return notify('Enam pilihan wajib terisi dan berbeda.');review(vals)}}
function review(vals){show(`${steps(1)}<h1>Sudah sesuai seleramu?</h1><p>Urutan terkunci setelah dikirim ke B. Periksa sekarang agar penilaian tetap adil.</p>${vals.map((v,i)=>`<div class="rank"><b>${i}</b><span>${esc(v)}</span></div>`).join('')}<div class="toolbar"><button id="edit">Ubah</button><button id="lock" class="primary">Kunci & sembunyikan</button></div>`);btn('edit',()=>write(vals));btn('lock',()=>{const mixed=shuffle(vals);state.items=mixed;state.truth=vals.map(v=>mixed.indexOf(v));state.id=uid();state.turn=0;state.answers=[];if(state.mode==='single')nextGuesser();else host()})}
function rankUI(items,callback,title,sub){order=shuffle([0,1,2,3,4,5]);show(`${steps(2)}<h1>${esc(title)}</h1><p>${esc(sub)}</p><div id="ranks"></div><p class="small">Gunakan ↑ ↓ untuk mengubah posisi. Atas = 0, bawah = 5.</p><button class="primary" id="submit">Periksa tebakan →</button>`);const draw=()=>{$('#ranks').innerHTML=order.map((id,i)=>`<div class="rank"><b>${i}</b><span class="word">${esc(items[id])}</span><button data-i="${i}" data-d="-1" aria-label="Naikkan ${esc(items[id])}" ${i===0?'disabled':''}>↑</button><button data-i="${i}" data-d="1" aria-label="Turunkan ${esc(items[id])}" ${i===5?'disabled':''}>↓</button></div>`).join('');$('#ranks').querySelectorAll('button').forEach(b=>b.onclick=()=>{const i=+b.dataset.i,j=i+(+b.dataset.d);[order[i],order[j]]=[order[j],order[i]];draw();const focus=$('#ranks').querySelector(`[data-i="${j}"][data-d="${b.dataset.d}"]`);if(focus&&!focus.disabled)focus.focus()})};draw();btn('submit',()=>{const answer=[...order];show(`<h1>Kunci tebakan ini?</h1>${answer.map((id,i)=>`<div class="rank"><b>${i}</b><span>${esc(items[id])}</span></div>`).join('')}<div class="toolbar"><button id="back">Ubah tebakan</button><button id="confirm" class="primary">Ya, kunci</button></div>`);btn('back',()=>{rankUI(items,callback,title,sub);order=answer;draw()});btn('confirm',()=>callback(answer))})}
function nextGuesser(){if(state.turn>=state.bs.length)return shield(state.a,revealReady,'Semua tebakan terkunci. A membuka hasil untuk seluruh pemain.');const name=state.bs[state.turn];shield(name,()=>rankUI(state.items,ans=>{state.answers.push({name,order:ans});state.turn++;nextGuesser()},`Tebakan ${name}`,`Urutkan ${state.category} sesuai selera ${state.a}.`))}
function revealReady(){show(`${steps(3)}<div class="center panel"><span class="eyebrow">${state.answers.length} tebakan terkunci</span><h1>Siapa yang paling kenal ${esc(state.a)}?</h1><p>Pastikan semua pemain sudah berkumpul. Urutan A tetap sesuai saat dikunci.</p><button class="primary" id="reveal">Buka semua hasil ♥</button></div>`);btn('reveal',results)}
function host(){const data={type:'challenge',id:state.id,a:state.a,category:state.category,items:state.items,players:state.bs},code=pack(data);show(`${steps(2)}<h1>Bagikan ke para penebak.</h1><span class="badge">A: ${esc(state.a)} · ${esc(state.category)}</span><div class="panel">${transfer(code,'tantangan.fk')}</div><h2>Terima jawaban B</h2><p>${state.answers.length}/${state.bs.length} masuk. ${esc(state.bs.filter(n=>!state.answers.some(a=>a.name===n)).join(', '))||'Semua selesai!'}</p><div class="panel">${importUI()}<button id="receive" class="primary" style="margin-top:16px">Masukkan jawaban</button></div><button id="reveal" ${state.answers.length!==state.bs.length?'disabled':''}>Lanjut ke reveal →</button><p class="small">Biarkan halaman A terbuka sampai ronde selesai. Kode tantangan hanya berisi pilihan acak, tanpa urutan rahasia A.</p>`);wireTransfer(code,'tantangan.fk');wireImport();btn('receive',()=>guard(()=>{const o=unpack($('#incoming').value,'answer');if(o.id!==state.id)throw Error('Jawaban ini berasal dari ronde lain.');if(!state.bs.includes(o.name)||!validOrder(o.order))throw Error('Nama atau urutan jawaban tidak valid.');if(state.answers.some(a=>a.name===o.name))throw Error('Pemain ini sudah mengirim. Jawaban pertama tetap terkunci.');state.answers.push({name:o.name,order:o.order});host();notify('Jawaban diterima.')}));btn('reveal',revealReady)}
function join(){show(`<span class="eyebrow">PERANGKAT B</span><h1>Buka tantangan A.</h1><div class="panel">${importUI()}<button id="load" class="primary" style="margin-top:16px">Buka tantangan</button></div>`);wireImport();btn('load',()=>guard(()=>{const o=unpack($('#incoming').value,'challenge');const text=v=>typeof v==='string'&&v.trim().length>0&&v.length<=80;if(!text(o.a)||!text(o.category)||!Array.isArray(o.items)||o.items.length!==6||!o.items.every(text)||new Set(o.items).size!==6||!Array.isArray(o.players)||o.players.length<1||o.players.length>11||!o.players.every(text)||new Set(o.players).size!==o.players.length)throw Error('Isi tantangan tidak valid.');challenge=o;show(`<h1>Kamu siapa?</h1><p>Kategori ${esc(o.category)} · Tebak selera ${esc(o.a)}</p><label for="who">Nama penebak / tim</label><select id="who">${o.players.map(p=>`<option>${esc(p)}</option>`).join('')}</select><button class="primary" id="go" style="margin-top:20px">Mulai menebak</button>`);btn('go',()=>{const name=$('#who').value;rankUI(o.items,ans=>{const code=pack({type:'answer',id:o.id,name,order:ans});show(`<span class="eyebrow">TEBAKAN TERKUNCI</span><h1>Kirim jawaban ke A.</h1><p>${esc(name)}, bagikan kode atau berkas ini. A akan menghitung hasil setelah seluruh jawaban masuk.</p><div class="panel">${transfer(code,'jawaban.fk')}</div><button id="another">Buka tantangan berikutnya</button>`);wireTransfer(code,'jawaban.fk');btn('another',join)},`Tebakan ${name}`,`Urutkan ${o.category} sesuai selera ${o.a}.`)})}))}
function results(){const ranked=state.answers.map(a=>({...a,points:score(state.truth,a.order),exact:a.order.filter((id,i)=>state.truth[i]===id).length})).sort((a,b)=>b.points-a.points);ranked.forEach(a=>state.totals[a.name]+=a.points);const top=ranked[0].points;show(`${steps(3)}<span class="eyebrow">HASIL RONDE ${state.round}</span><h1>${ranked.filter(a=>a.points===top).map(a=>esc(a.name)).join(' & ')}<br><span class="accent">paling dekat!</span></h1><p>Kategori ${esc(state.category)} · A: ${esc(state.a)}</p><div class="grid">${ranked.map(a=>`<div class="panel ${a.points===top?'winner':''}"><strong>${esc(a.name)}</strong><div class="score">${a.points} <span class="small">/ 30 poin</span></div><span class="small">${a.exact}/6 posisi tepat · total selisih ${30-a.points}</span></div>`).join('')}</div><div class="panel"><h2>Urutan asli & tebakan</h2><div class="tablewrap"><table><thead><tr><th>Rank</th><th>${esc(state.a)}</th>${ranked.map(a=>`<th>${esc(a.name)}</th>`).join('')}</tr></thead><tbody>${state.truth.map((id,i)=>`<tr><td>${i}</td><td>${esc(state.items[id])}</td>${ranked.map(a=>`<td>${a.order[i]===id?'✓ ':''}${esc(state.items[a.order[i]])}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div><div class="panel"><h2>Total sesi</h2>${[...state.players].sort((a,b)=>state.totals[b]-state.totals[a]).map(n=>`<p>${esc(n)} <strong class="accent">${state.totals[n]} poin</strong></p>`).join('')}<p class="small">A tidak mendapat poin saat menjadi pemilik urutan. Bandingkan total setelah kelipatan ${state.players.length} ronde agar setiap orang sama sering menjadi A.</p></div><div class="toolbar"><button id="again" class="primary">Ronde berikutnya · ganti A</button><button id="finish">Selesai</button></div>`);btn('again',()=>{state.round++;category()});btn('finish',home)}
$('#theme').onclick=()=>{document.body.classList.toggle('light');try{localStorage.setItem('fk-theme',document.body.classList.contains('light')?'light':'dark')}catch{}};
try{if(localStorage.getItem('fk-theme')==='light')document.body.classList.add('light')}catch{}
$('#home').onclick=e=>{e.preventDefault();if(confirm('Kembali ke awal? Permainan yang sedang berlangsung akan hilang.'))home()};
window.addEventListener('beforeunload',e=>{if(state.id){e.preventDefault();e.returnValue=''}});
home();
