'use strict';
const $=s=>document.querySelector(s),app=$('#app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=null,unlocked=false,screen='home',timer=null,manage=-1,blindOrder=[],peek=null;
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(timer);timer=setTimeout(()=>$('#toast').style.display='none',2800)}
function show(s){app.innerHTML=s}
function bind(id,fn){const x=$('#'+id);if(x)x.onclick=fn}
function cardLabel(type){return type==='flower'?'Bunga':type==='trap'?'Duri':type==='oracle'?'Oracle':type==='joker'?'Joker':''}
function face(type){const cls=type==='trap'?'trap':type==='back'?'back':type==='oracle'?'oracle':type==='joker'?'joker':'';const sym=type==='flower'?'❀':type==='trap'?'✹':type==='oracle'?'✧':type==='joker'?'✥':'◇';return `<span class="disc ${cls}" aria-hidden="true">${sym}</span>`}
function compBadge(key){return key==='chaos'?'⚡ Chaos':key}
function save(){try{localStorage.setItem('bd-cards-v3',JSON.stringify(state))}catch{}}
function step(a){try{state=CardTable.apply(state,a);save();unlocked=false;render();return true}catch(e){toast(e.message);return false}}
function home(){screen='home';unlocked=false;manage=-1;show(`<div class="intro"><div><span class="eyebrow">Kartu digital untuk bermain tatap muka</span><h1>HP jadi kartu.<br><em class="accent">Kalian yang bermain.</em></h1><p>Pasang rahasia. Bet langsung. Buka satu per satu.</p></div><div class="sample" aria-label="Kartu bunga, kartu tertutup, kartu duri">${face('flower')}${face('back')}${face('trap')}</div></div><div class="grid"><button id="single" class="mode"><span class="badge">SATU PERANGKAT</span><strong>HP dioper</strong><small>Satu HP menyimpan kartu semua pemain. Pasang, tutup, lalu oper.</small></button><button id="personal" class="mode"><span class="badge">MASING-MASING PERANGKAT</span><strong>HP saya</strong><small>HP ini hanya menyimpan kartuku. Saat bet, kumpulkan HP di tengah.</small></button></div><div class="panel"><p>Bet dan siapa yang membuka disepakati langsung. Setiap HP dapat dimainkan sepenuhnya offline.</p><div class="row"><button id="rules" class="quiet">Cara menggunakan</button><span id="resume"></span></div></div>`);bind('single',()=>setup('single'));bind('personal',()=>setup('personal'));bind('rules',()=>$('#guide').showModal());try{const s=JSON.parse(localStorage.getItem('bd-cards-v3')||'null');if(CardTable.valid(s)){$('#resume').innerHTML='<button id="continue">Lanjutkan kartu tersimpan</button>';bind('continue',()=>{state=s;unlocked=false;render()})}}catch{}}
function setup(mode){screen='setup';const compLabels={'3+1':'3+1 · klasik (3 bunga, 1 duri)','4+1':'4+1 (4 bunga, 1 duri)','chaos':'⚡ Chaos (3 bunga, Oracle, Joker, 1 duri)'};const compHints={'3+1':'Susunan asli: 3 bunga aman, 1 duri, per pemain.','4+1':'4 bunga aman, 1 duri, per pemain.','chaos':'Per pemain: 3 bunga + 1 Oracle (saat dibuka, boleh intip satu kartu tertutup pemain lain) + 1 Joker (saat dibuka, bunga↔duri tukar makna sampai ronde ini selesai — kalian yang sepakati) + 1 duri.'};const compOptions=Object.keys(CardTable.COMPOSITIONS).map(k=>`<option value="${k}">${compLabels[k]}</option>`).join('');show(`<span class="eyebrow">${mode==='single'?'Satu HP dioper':'Satu set kartu di HP ini'}</span><h1>${mode==='single'?'Siapa yang ikut bermain?':'Kartu ini milik siapa?'}</h1><form id="setup" class="panel">${mode==='single'?'<label for="count">Jumlah pemain</label><select id="count"><option>3</option><option>4</option><option>5</option><option>6</option></select><div class="name-fields" id="names"></div><p class="small">Urutan di atas menjadi urutan oper HP. Giliran dapat diubah sesuai kesepakatan.</p>':'<label for="name">Nama di HP ini</label><input id="name" maxlength="24" placeholder="Nama saya" autocomplete="nickname"><p>Cukup namamu sendiri. Teman-teman membuka aplikasi yang sama di HP masing-masing.</p>'}<label for="comp">Susunan kartu</label><select id="comp">${compOptions}</select><p class="small" id="compHint"></p><button class="primary" style="margin-top:18px">Siapkan kartu →</button></form>`);const updateHint=()=>{$('#compHint').textContent=compHints[$('#comp').value]};$('#comp').onchange=updateHint;updateHint();if(mode==='single'){const draw=()=>{const old=[...document.querySelectorAll('.player-name')].map(e=>e.value);$('#names').innerHTML=Array.from({length:+$('#count').value},(_,i)=>`<div><label for="name${i}">Pemain ${i+1}</label><input id="name${i}" class="player-name" maxlength="24" value="${esc(old[i]||'Pemain '+(i+1))}" required></div>`).join('')};$('#count').onchange=draw;draw()}$('#setup').onsubmit=e=>{e.preventDefault();try{const names=mode==='single'?[...document.querySelectorAll('.player-name')].map(e=>e.value.trim()):[$('#name').value.trim()||'Kartu saya'];state=CardTable.create(mode,names,$('#comp').value);unlocked=false;save();render()}catch(e){toast(e.message)}}}
function render(){screen='game';manage=-1;blindOrder=[];peek=null;if(state.phase==='place')placement();else if(state.phase==='reveal')table();else between()}
function placement(){const v=CardTable.publicView(state),p=v.players[v.turn],personal=state.mode==='personal',allEmpty=state.players.every(p=>!CardTable.hand(p).length);const name=esc(p.name);const betText=personal?'Taruh di tengah · mode buka':'Ada bet · buka meja';
show(`<div class="toolbar"><div><span class="eyebrow">${personal?'HP milik '+name:'Satu HP · pass & play'}</span><h1>${unlocked?'Tangan '+name:personal?'Tumpukan saya.':'Pasang & oper.'}</h1></div><div class="row">${v.comp==='chaos'?'<span class="badge">⚡ Chaos</span>':''}<span class="badge">Ronde ${v.round}</span></div></div><section class="panel center handoff" id="hand-area"></section><div class="mini-stacks">${v.players.map(p=>`<span>${esc(p.name)} · ${p.stack.length} di meja</span>`).join('')}</div><div class="panel"><p>${personal?'Saat bet selesai disepakati, masuk mode buka dan letakkan HP ini bersama HP lain di tengah.':'Begitu ada bet, pindah ke meja kartu. Tentukan tawaran akhir dan siapa yang membuka secara lisan.'}</p><button id="bet" class="primary full-width" ${CardTable.total(state)?'':'disabled'}>${betText}</button></div>${!personal&&!allEmpty?`<details class="panel"><summary>Ubah giliran sesuai kesepakatan</summary><label for="turn">Pemegang HP berikutnya</label><select id="turn">${v.players.map((p,i)=>p.handCount?`<option value="${i}" ${i===v.turn?'selected':''}>${esc(p.name)}</option>`:'').join('')}</select><button id="setTurn" style="margin-top:14px">Oper ke pemain ini</button></details>`:''}`);
const area=$('#hand-area');if(!unlocked){area.innerHTML=`${face('back')}<h1>${allEmpty?'Semua kartu terpasang.':personal?(p.stack.length?'Kartu sudah tertutup.':'Siap saat giliranmu.'):name}</h1><p>${allEmpty?'Silakan lanjutkan bet langsung di meja.':personal?'Tunggu giliran nyata. Buka tangan hanya saat kamu ingin memasang kartu.':'Serahkan HP kepada pemain ini. Pemain lain lihat ke arah lain.'}</p>${!allEmpty?`<button id="unlock" class="primary">${personal?'Giliran saya · pilih kartu':'Saya '+name+' · buka tangan'}</button>`:''}`;bind('unlock',()=>{unlocked=true;placement()})}else{const hand=CardTable.hand(state.players[state.turn]);area.innerHTML=`<span class="eyebrow">Hanya ${name} yang melihat</span><p>Pilih satu kartu untuk dipasang tertutup.</p><div class="hand">${hand.map(c=>`<button class="place" data-card="${c.id}">${face(c.type)}<span>${cardLabel(c.type)}</span></button>`).join('')}</div><button id="hide" class="quiet">Tutup tangan</button>`;area.querySelectorAll('.place').forEach(b=>b.onclick=()=>{step({type:'place',card:+b.dataset.card})});bind('hide',()=>{unlocked=false;placement()})}
bind('bet',()=>step({type:'reveal'}));bind('setTurn',()=>step({type:'turn',player:+$('#turn').value}));}
function table(){const v=CardTable.publicView(state),personal=v.mode==='personal',chaos=v.comp==='chaos',opened=v.players.reduce((n,p)=>n+p.stack.filter(c=>c.up).length,0);show(`<div class="toolbar"><div><span class="eyebrow">${personal?'HP milik '+esc(v.players[0].name):'Seluruh tumpukan pemain'}</span><h1>${personal?'Taruh HP di tengah.':'Meja siap dibuka.'}</h1></div><div class="row">${chaos?'<span class="badge">⚡ Chaos</span>':''}<span class="badge">${opened}/${CardTable.total(state)} terbuka</span></div></div><p class="helper">${personal?'Tumpukan di HP ini saja. Orang yang kalian pilih boleh mengetuk kartu teratas, lalu berpindah ke HP lain.':'Serahkan HP ke orang yang kalian pilih. Ketuk kartu teratas pada tumpukan yang ingin dibuka.'}</p>${chaos?`<div class="panel"><p>Mode Chaos aktif. Kalau ada yang baru buka Oracle, boleh intip satu kartu tertutup — sepakati sendiri siapa yang berhak pakai. Kalau ada yang buka Joker, bunga↔duri tukar makna sampai ronde ini selesai.</p><button id="oracleBtn">✧ Intip kartu tertutup</button></div>`:''}<div class="table ${personal?'personal':''}">${v.players.map((p,player)=>{let top=p.stack.findLastIndex(c=>!c.up);return `<section class="mat"><div class="mat-head"><h3>${esc(p.name)}</h3><span class="badge">${p.stack.length} kartu</span></div><div class="pile">${p.stack.length?[...p.stack].map((c,index)=>({c,index})).reverse().map(({c,index})=>`<div class="card-wrap ${index===top?'clickable':''}">${c.up?`${face(c.type)}<span class="small">${cardLabel(c.type)}</span>`:`<button class="flip" data-player="${player}" data-index="${index}" ${index===top?'':'disabled'} aria-label="Buka kartu ${index+1} milik ${esc(p.name)}">${face('back')}</button><span class="small">${index===top?'Ketuk untuk buka':'Tertutup'}</span>`}</div>`).join(''):'<span class="empty">Belum memasang kartu.</span>'}</div>${top>=0?`<button class="open-top flip primary" data-player="${player}" data-index="${top}">Buka kartu teratas</button>`:'<p class="small">'+(p.stack.length?'Semua kartu tumpukan ini terbuka.':'')+'</p>'}</section>`}).join('')}</div><div class="row finish-actions"><button id="finish" class="quiet">Selesai ronde</button>${opened===0?'<button id="resumePlace" class="text-button">Kembali memasang kartu</button>':''}</div><p class="small">Kalian menentukan kapan berhenti. Buka tumpukan sendiri dahulu sesuai aturan yang disepakati.</p>`);app.querySelectorAll('.flip').forEach(b=>b.onclick=()=>{const player=+b.dataset.player,index=+b.dataset.index,type=state.players[player].stack[index].type;if(step({type:'flip',player,index})){if(type==='trap')toast('Duri terbuka.');else if(type==='oracle')toast('Oracle terbuka! Boleh intip satu kartu tertutup.');else if(type==='joker')toast('Joker terbuka! Bunga ↔ duri tukar makna sampai ronde ini selesai.')}});bind('finish',()=>step({type:'finish'}));bind('resumePlace',()=>step({type:'resumePlace'}));if(chaos)bind('oracleBtn',openPeek);}
function openPeek(){peek={target:state.mode==='personal'?0:null,index:null};renderPeek()}
function closePeek(){peek=null;table()}
function renderPeek(){if(peek.target===null){show(`<span class="eyebrow">Oracle</span><h1>Intip kartu siapa?</h1><div class="grid">${state.players.map((p,i)=>{const closed=p.stack.filter(c=>!c.up).length;return `<button class="mode peekTarget" data-i="${i}" ${closed?'':'disabled'}><strong>${esc(p.name)}</strong><small>${closed} kartu tertutup</small></button>`}).join('')}</div><button id="cancelPeek" class="text-button">Batal</button>`);app.querySelectorAll('.peekTarget').forEach(b=>b.onclick=()=>{peek.target=+b.dataset.i;renderPeek()});bind('cancelPeek',closePeek);return}
if(peek.index===null){const p=state.players[peek.target];const closedSlots=p.stack.map((c,idx)=>idx).filter(idx=>!p.stack[idx].up);show(`<span class="eyebrow">Oracle</span><h1>Pilih kartu tertutup ${esc(p.name)}.</h1><div class="hand">${closedSlots.length?closedSlots.map(idx=>`<button class="place peekCard" data-idx="${idx}">${face('back')}<span>Kartu ${idx+1}</span></button>`).join(''):'<p>Tidak ada kartu tertutup.</p>'}</div><button id="cancelPeek" class="text-button">Batal</button>`);app.querySelectorAll('.peekCard').forEach(b=>b.onclick=()=>{peek.index=+b.dataset.idx;renderPeek()});bind('cancelPeek',closePeek);return}
const c=state.players[peek.target].stack[peek.index];show(`<section class="panel center protect"><span class="eyebrow">Hanya kamu yang melihat</span>${face(c.type)}<h1>${cardLabel(c.type)}</h1><button id="hidePeek" class="primary">Sembunyikan lagi</button></section>`);bind('hidePeek',closePeek);}
function between(){const personal=state.mode==='personal',alive=state.players.map((p,i)=>p.cards.length?i:-1).filter(i=>i>=0);show(`<span class="eyebrow">Kartu kembali ke tangan</span><h1>Siapkan ronde berikutnya.</h1><p>Sepakati hasilnya langsung. Kartu hanya dikurangi jika kalian memilih penalti di bawah.</p><section class="panel">${state.players.map((p,i)=>`<div class="player-row"><div><strong>${esc(p.name)}</strong><div class="small">${p.cards.length} kartu tersisa</div></div><button class="manage quiet" data-player="${i}">Kelola kartu</button></div>`).join('')}</section><section class="panel">${!personal&&alive.length?`<label for="starter">Siapa yang memasang pertama?</label><select id="starter">${alive.map(i=>`<option value="${i}">${esc(state.players[i].name)}</option>`).join('')}</select>`:''}<button id="next" class="primary full-width" style="margin-top:16px" ${alive.length?'':'disabled'}>Mulai ronde berikutnya</button>${!alive.length?'<p class="small">Kartu habis. Gunakan Kelola kartu untuk mengembalikan set, atau mulai permainan baru.</p>':''}</section><button id="newGame" class="text-button">Selesai bermain · beranda</button>`);app.querySelectorAll('.manage').forEach(b=>b.onclick=()=>manageGate(+b.dataset.player));bind('next',()=>step({type:'next',player:personal?0:+$('#starter').value}));bind('newGame',home);}
function manageGate(i){manage=i;const p=state.players[i];show(`<section class="panel center protect"><span class="eyebrow">Pengaturan kartu ${esc(p.name)}</span><h1>Berikan ke pemilik HP / kartu.</h1><p>Kelola kartu setelah hasil dan penalti kalian sepakati.</p><div class="row"><button id="choose" class="primary">Saya ${esc(p.name)} · pilih sendiri</button><button id="blind">Pemain lain pilih acak tertutup</button><button id="cancel" class="quiet">Kembali</button></div></section>`);bind('choose',()=>manageCards(i));bind('blind',()=>blindCards(i));bind('cancel',render);}
function manageCards(i){manage=i;const p=state.players[i],size=CardTable.deckSize(state.comp);show(`<section class="panel center protect"><span class="eyebrow">Rahasia ${esc(p.name)}</span><h1>Kartu yang tersisa.</h1><p>Ketuk satu kartu jika kalian memutuskan kartu itu dibuang.</p><div class="hand">${p.cards.map(c=>`<button class="remove" data-card="${c.id}">${face(c.type)}<span>Buang ${cardLabel(c.type).toLowerCase()}</span></button>`).join('')||'<p>Tidak ada kartu tersisa.</p>'}</div><div class="row"><button id="cancel" class="quiet">Selesai · tutup kartu</button><button id="restore" class="text-button">Kembalikan set ${size} kartu</button></div></section>`);app.querySelectorAll('.remove').forEach(b=>b.onclick=()=>{if(step({type:'remove',player:i,card:+b.dataset.card}))toast('Satu kartu dibuang.');});bind('cancel',render);bind('restore',()=>{if(confirm('Kembalikan set kartu awal untuk pemain ini?'))step({type:'restore',player:i})});}
function blindCards(i){manage=i;blindOrder=state.players[i].cards.map(c=>c.id);for(let j=blindOrder.length-1;j>0;j--){const k=Math.floor(Math.random()*(j+1));[blindOrder[j],blindOrder[k]]=[blindOrder[k],blindOrder[j]]}show(`<section class="panel center protect"><span class="eyebrow">Pilihan tertutup</span><h1>Pilih satu kartu ${esc(state.players[i].name)}.</h1><p>Berikan HP kepada orang yang kalian sepakati untuk memilih. Kartu sudah diacak dan tidak akan ditampilkan saat dibuang.</p><div class="hand">${blindOrder.map((_,slot)=>`<button class="blind" data-slot="${slot}">${face('back')}<span>Pilih ${slot+1}</span></button>`).join('')||'<p>Tidak ada kartu tersisa.</p>'}</div><button id="cancel" class="quiet">Batal</button></section>`);app.querySelectorAll('.blind').forEach(b=>b.onclick=()=>{const card=blindOrder[+b.dataset.slot];if(step({type:'remove',player:i,card}))toast('Satu kartu dibuang tanpa dibuka.')});bind('cancel',render);}
$('#theme').onclick=()=>{document.body.classList.toggle('light');try{localStorage.setItem('bd-cards-theme',document.body.classList.contains('light')?'light':'dark')}catch{}};
$('#help').onclick=()=>$('#guide').showModal();$('#closeGuide').onclick=()=>$('#guide').close();$('#home').onclick=()=>{if(screen==='game'&&state){save()}home()};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state&&screen==='game'){unlocked=false;if(manage>=0){manage=-1;render()}else if(state.phase==='place')placement()}});
try{if(localStorage.getItem('bd-cards-theme')==='light')document.body.classList.add('light')}catch{}
home();
