
const STORAGE='miau-crack-4-v1', $=s=>document.querySelector(s);
const E={app:$('#app'),theme:$('#themeBtn'),sound:$('#soundBtn'),reset:$('#resetBtn'),toast:$('#toast')};
let prefs=loadPrefs(),game=null,input=[] ,audio=null;
function loadPrefs(){try{return {...{theme:'light',sound:true,names:['Oyen','Mochi']},...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return{theme:'light',sound:true,names:['Oyen','Mochi']}}}
function savePrefs(){localStorage.setItem(STORAGE,JSON.stringify(prefs))}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(m){E.toast.textContent=m;E.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.classList.remove('show'),1500)}
function beep(f=650,d=.06){if(!prefs.sound)return;try{audio||=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(.05,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function applyTheme(){document.documentElement.dataset.theme=prefs.theme;E.theme.textContent=prefs.theme==='dark'?'☀️':'🌙';E.sound.textContent=prefs.sound?'🔊':'🔇'}
function codeCells(arr,states=null,masked=false){return `<div class="code-row">${[0,1,2,3].map(i=>`<div class="code-cell ${states?states[i]:'empty'}">${arr[i]!==undefined?(masked?'•':arr[i]):'_'}</div>`).join('')}</div>`}
function keypad(disabledDigits=[]){return `<div class="keypad">${[0,1,2,3,4,5,6,7,8,9].map(n=>`<button class="key" data-digit="${n}" ${disabledDigits.includes(n)?'disabled':''}>${n}</button>`).join('')}<button class="key action" data-back>⌫</button><button class="key action" data-clear>Clear</button></div>`}
function home(){return `<section class="hero"><div class="panel hero-main"><div class="eyebrow">CODE DUEL</div><div class="hero-title">4 digit.<br>1 lawan.</div><p class="hero-copy">Kalian masing-masing membuat kode 4 digit tanpa angka kembar. Tebak posisi lawan secara bergantian. Yang tepat langsung hijau; yang belum tepat tetap gelap.</p><div class="button-row"><button class="primary-btn big" id="setupBtn">🔐 Mulai Duel</button></div><div class="note">Satu ronde selalu memberi kedua pemain jumlah kesempatan yang sama. Kalau keduanya memecahkan kode pada ronde yang sama, hasilnya seri.</div></div><div class="panel"><div class="eyebrow">ATURAN</div><div class="rule-grid"><div class="rule"><b>4 digit unik</b><span>0 boleh dipakai, angka tidak boleh kembar.</span></div><div class="rule"><b>🟩 Exact only</b><span>Hijau hanya jika digit dan posisinya tepat.</span></div><div class="rule"><b>History privat</b><span>Setiap pemain melihat riwayat tebakannya sendiri.</span></div><div class="rule"><b>Round fairness</b><span>Pemain kedua tetap mendapat giliran jika pemain pertama berhasil.</span></div></div></div></section>`}
function setup(){return `<section class="panel"><div class="eyebrow">SETUP</div><h2>Siapa yang duel?</h2><div class="setup-grid"><label class="field">Player A<input id="nameA" maxlength="24" value="${esc(prefs.names[0])}"></label><label class="field">Player B<input id="nameB" maxlength="24" value="${esc(prefs.names[1])}"></label></div><div class="button-row"><button class="primary-btn big" id="beginBtn">🎲 Kunci Kode</button><button class="secondary-btn" id="cancelBtn">Batal</button></div></section>`}
function passSecret(){const who=game.secretIndex;return `<section class="panel"><div class="pass-screen"><div class="big-emoji">🔒🙈</div><div class="eyebrow">RAHASIA</div><div class="player-name">${esc(game.names[who])}</div><p class="hero-copy">Pastikan hanya ${esc(game.names[who])} yang melihat layar.</p><button class="primary-btn big" id="enterSecretBtn">Saya ${esc(game.names[who])} → masukkan kode</button></div></section>`}
function secretEntry(){return `<section class="panel"><div class="secret-screen"><div class="eyebrow">BUAT SECRET CODE</div><div class="player-name">${esc(game.names[game.secretIndex])}</div><p class="hero-copy">Pilih 4 digit unik. 0 boleh di posisi pertama.</p>${codeCells(input,null,true)}${keypad(input)}<div class="button-row"><button class="primary-btn big" id="lockSecretBtn" ${input.length!==4?'disabled':''}>🔒 LOCK CODE</button></div></div></section>`}
function passTurn(){const a=game.turn;return `<section class="panel"><div class="pass-screen"><div class="big-emoji">😼📱</div><div class="round-pill">ROUND ${game.round}</div><div class="player-name">Giliran ${esc(game.names[a])}</div><p class="hero-copy">Berikan device ke ${esc(game.names[a])}. Jangan biarkan lawan melihat history tebakan.</p><button class="primary-btn big" id="openTurnBtn">Saya ${esc(game.names[a])} → mulai menebak</button></div></section>`}
function knownCode(player){const hist=game.history[player],known=['_','_','_','_'];for(const h of hist)h.states.forEach((s,i)=>{if(s==='exact')known[i]=h.guess[i]});return known}
function historyMarkup(player){const hist=[...game.history[player]].reverse();if(!hist.length)return `<div class="note">Belum ada attempt.</div>`;return `<div class="history">${hist.map(h=>`<div class="history-row">${codeCells(h.guess,h.states)}<div class="history-meta">Round ${h.round}<br><b>${h.exact}/4 exact</b></div></div>`).join('')}</div>`}
function turnScreen(){const a=game.turn,b=1-a,known=knownCode(a);return `<section class="panel"><div class="turn-screen"><div class="round-pill">ROUND ${game.round} • ${esc(game.names[a])} menebak ${esc(game.names[b])}</div><div class="score-grid"><div class="score-card active"><b>${esc(game.names[a])}</b><span>${game.history[a].length} attempts</span></div><div class="score-card"><b>${esc(game.names[b])}</b><span>${game.history[b].length} attempts</span></div></div><div class="known-label">POSISI YANG SUDAH TERBUKTI</div>${codeCells(known.map(x=>x==='_ '?undefined:x).map(x=>x==='_ '?undefined:x))}<div class="known-label">TEBAKAN SEKARANG</div>${codeCells(input)}${keypad(input)}<div class="button-row"><button class="primary-btn big" id="guessBtn" ${input.length!==4?'disabled':''}>ENTER GUESS</button></div><div class="history-wrap"><div class="history-title"><b>History ${esc(game.names[a])}</b><span class="eyebrow">PRIVAT</span></div>${historyMarkup(a)}</div></div></section>`}
function evaluate(guess,secret){const states=guess.map((d,i)=>d===secret[i]?'exact':'miss');return{states,exact:states.filter(x=>x==='exact').length}}
function feedbackScreen(){const f=game.lastFeedback,a=f.player,b=1-a;return `<section class="panel"><div class="result-screen"><div class="round-pill">ROUND ${f.round}</div><div class="eyebrow">HASIL TEBAKAN ${esc(game.names[a])}</div>${codeCells(f.guess,f.states)}<div class="feedback">${f.exact}/4 posisi tepat</div>${f.exact===4?`<h2>🔓 CODE CRACKED!</h2><p class="hero-copy">${game.pendingTieCheck?`${esc(game.names[b])} tetap mendapat kesempatan pada ronde yang sama.`:'Tunggu hasil akhir ronde.'}</p>`:`<p class="hero-copy">Kotak gelap hanya berarti posisinya belum tepat; game tidak memberi tahu apakah digit itu ada di posisi lain.</p>`}<button class="primary-btn big" id="continueBtn">${game.phaseAfterFeedback==='final'?'🏆 Lihat Hasil':'📱 Pass Device'}</button></div></section>`}
function finalScreen(){const w=game.winner;let title=w==='draw'?'🤝 SERI!':`🏆 ${esc(game.names[w])} MENANG!`;let sub=w==='draw'?`Keduanya memecahkan kode pada Round ${game.round}.`:`${esc(game.names[w])} memecahkan kode lebih dulu dalam ronde yang seimbang.`;return `<section class="panel"><div class="result-screen"><div class="eyebrow">FINAL RESULT</div><div class="win-title">${title}</div><p class="hero-copy">${sub}</p><div class="secret-reveal">${[0,1].map(i=>`<div class="secret-card"><b>${esc(game.names[i])}</b>${codeCells(game.secrets[i])}<span class="eyebrow">SECRET CODE</span></div>`).join('')}</div><div class="button-row"><button class="primary-btn big" id="rematchBtn">🔁 Rematch</button><button class="secondary-btn" id="homeBtn">🏠 Beranda</button></div></div></section>`}
function render(){E.app.innerHTML=!game?home():game.phase==='setup'?setup():game.phase==='passSecret'?passSecret():game.phase==='secret'?secretEntry():game.phase==='passTurn'?passTurn():game.phase==='turn'?turnScreen():game.phase==='feedback'?feedbackScreen():finalScreen();bind()}
function bind(){
 $('#setupBtn')?.addEventListener('click',()=>{game={phase:'setup'};render()});
 $('#cancelBtn')?.addEventListener('click',()=>{game=null;render()});
 $('#beginBtn')?.addEventListener('click',()=>{let a=$('#nameA').value.trim()||'Player A',b=$('#nameB').value.trim()||'Player B';prefs.names=[a,b];savePrefs();game={phase:'passSecret',names:[a,b],secrets:[null,null],secretIndex:0,history:[[],[]],turn:0,round:1,solvedRound:[null,null],winner:null};input=[];render()});
 $('#enterSecretBtn')?.addEventListener('click',()=>{input=[];game.phase='secret';render()});
 document.querySelectorAll('[data-digit]').forEach(btn=>btn.onclick=()=>{const n=Number(btn.dataset.digit);if(input.length<4&&!input.includes(n)){input.push(n);beep(560,.03);render()}});
 document.querySelector('[data-back]')?.addEventListener('click',()=>{input.pop();render()});document.querySelector('[data-clear]')?.addEventListener('click',()=>{input=[];render()});
 $('#lockSecretBtn')?.addEventListener('click',()=>{game.secrets[game.secretIndex]=[...input];input=[];if(game.secretIndex===0){game.secretIndex=1;game.phase='passSecret'}else{game.phase='passTurn';game.turn=0}beep(760,.07);render()});
 $('#openTurnBtn')?.addEventListener('click',()=>{input=[];game.phase='turn';render()});
 $('#guessBtn')?.addEventListener('click',()=>{const a=game.turn,b=1-a,r=evaluate(input,game.secrets[b]);const rec={guess:[...input],states:r.states,exact:r.exact,round:game.round};game.history[a].push(rec);if(r.exact===4)game.solvedRound[a]=game.round;game.lastFeedback={...rec,player:a};input=[];
   if(a===0){game.pendingTieCheck=r.exact===4;game.turn=1;game.phaseAfterFeedback='passTurn';}
   else{const aSolved=game.solvedRound[0]===game.round,bSolved=game.solvedRound[1]===game.round;if(aSolved||bSolved){game.winner=aSolved&&bSolved?'draw':(aSolved?0:1);game.phaseAfterFeedback='final'}else{game.round++;game.turn=0;game.phaseAfterFeedback='passTurn'}game.pendingTieCheck=false}game.phase='feedback';beep(r.exact===4?900:500,.08);render()});
 $('#continueBtn')?.addEventListener('click',()=>{game.phase=game.phaseAfterFeedback;render()});
 $('#rematchBtn')?.addEventListener('click',()=>{const names=[...game.names];game={phase:'passSecret',names,secrets:[null,null],secretIndex:0,history:[[],[]],turn:0,round:1,solvedRound:[null,null],winner:null};input=[];render()});
 $('#homeBtn')?.addEventListener('click',()=>{game=null;render()});
}
E.theme.onclick=()=>{prefs.theme=prefs.theme==='dark'?'light':'dark';savePrefs();applyTheme()};E.sound.onclick=()=>{prefs.sound=!prefs.sound;savePrefs();applyTheme();beep(700,.04)};E.reset.onclick=()=>{if(confirm('Mulai game baru? Progress sekarang akan hilang.')){game=null;input=[];render()}};applyTheme();render();
