
const STORAGE='duel-tebak-angka-v1', $=s=>document.querySelector(s);
const E={app:$('#app'),theme:$('#themeBtn'),sound:$('#soundBtn'),reset:$('#resetBtn'),toast:$('#toast')};
let prefs=loadPrefs(),game=null,input='',audio=null;
const PRESETS=[{label:'Mudah (1-50)',min:1,max:50},{label:'Normal (1-100)',min:1,max:100},{label:'Sulit (1-200)',min:1,max:200}];
function loadPrefs(){try{return {...{theme:'light',sound:true,names:['Player A','Player B'],presetIdx:1,customMin:1,customMax:100},...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return{theme:'light',sound:true,names:['Player A','Player B'],presetIdx:1,customMin:1,customMax:100}}}
function savePrefs(){localStorage.setItem(STORAGE,JSON.stringify(prefs))}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(m){E.toast.textContent=m;E.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.classList.remove('show'),1500)}
function beep(f=650,d=.06){if(!prefs.sound)return;try{audio||=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(.05,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function applyTheme(){document.documentElement.dataset.theme=prefs.theme;E.theme.textContent=prefs.theme==='dark'?'☀️':'🌙';E.sound.textContent=prefs.sound?'🔊':'🔇'}
function maxDigits(){return String(game.range.max).length}
function numberCells(str,masked=false){const len=maxDigits(),cells=[];for(let i=0;i<len;i++){const has=i<str.length;cells.push(`<div class="num-cell ${has?'':'empty'}">${has?(masked?'•':str[i]):'_'}</div>`)}return `<div class="number-display">${cells.join('')}</div>`}
function keypad(){const len=maxDigits();return `<div class="keypad">${[0,1,2,3,4,5,6,7,8,9].map(n=>`<button class="key" data-digit="${n}" ${input.length>=len?'disabled':''}>${n}</button>`).join('')}<button class="key action" data-back>⌫</button><button class="key action" data-clear>Clear</button></div>`}
function home(){return `<section class="hero"><div class="panel hero-main"><div class="eyebrow">NUMBER DUEL</div><div class="hero-title">1 angka.<br>1 lawan.</div><p class="hero-copy">Kalian masing-masing memilih 1 angka rahasia dalam rentang yang sama. Bergantian menebak angka lawan &mdash; sistem cuma bilang "lebih tinggi" atau "lebih rendah" sampai tepat.</p><div class="button-row"><button class="primary-btn big" id="setupBtn">🔢 Mulai Duel</button></div><div class="note">Satu ronde selalu memberi kedua pemain jumlah kesempatan yang sama. Kalau keduanya menebak tepat pada ronde yang sama, hasilnya seri.</div></div><div class="panel"><div class="eyebrow">ATURAN</div><div class="rule-grid"><div class="rule"><b>1 angka rahasia</b><span>Pilih dalam rentang yang disepakati, tidak boleh sama dengan lawan.</span></div><div class="rule"><b>🔼🔽 Petunjuk arah</b><span>Sistem hanya bilang lebih tinggi / lebih rendah, bukan "salah" biasa.</span></div><div class="rule"><b>History privat</b><span>Setiap pemain melihat riwayat tebakannya sendiri.</span></div><div class="rule"><b>Round fairness</b><span>Pemain kedua tetap mendapat giliran jika pemain pertama berhasil.</span></div></div></div></section>`}
function setup(){const p=prefs;return `<section class="panel"><div class="eyebrow">SETUP</div><h2>Siapa yang duel?</h2><div class="setup-grid"><label class="field">Player A<input id="nameA" maxlength="24" value="${esc(p.names[0])}"></label><label class="field">Player B<input id="nameB" maxlength="24" value="${esc(p.names[1])}"></label></div><div class="eyebrow">RENTANG ANGKA</div><div class="preset-row">${PRESETS.map((pr,i)=>`<button class="preset-btn ${p.presetIdx===i?'active':''}" data-preset="${i}">${pr.label}</button>`).join('')}<button class="preset-btn ${p.presetIdx===-1?'active':''}" data-preset="-1">Custom</button></div>${p.presetIdx===-1?`<div class="custom-range"><label class="field">Min<input id="customMin" type="number" value="${p.customMin}"></label><label class="field">Max<input id="customMax" type="number" value="${p.customMax}"></label></div>`:''}<div class="button-row"><button class="primary-btn big" id="beginBtn">🎲 Kunci Angka</button><button class="secondary-btn" id="cancelBtn">Batal</button></div></section>`}
function passSecret(){const who=game.secretIndex;return `<section class="panel"><div class="pass-screen"><div class="big-emoji">🔒🙈</div><div class="eyebrow">RAHASIA</div><div class="player-name">${esc(game.names[who])}</div><p class="hero-copy">Pastikan hanya ${esc(game.names[who])} yang melihat layar.</p><button class="primary-btn big" id="enterSecretBtn">Saya ${esc(game.names[who])} → masukkan angka</button></div></section>`}
function secretEntry(){const r=game.range;return `<section class="panel"><div class="secret-screen"><div class="eyebrow">BUAT ANGKA RAHASIA</div><div class="player-name">${esc(game.names[game.secretIndex])}</div><p class="hero-copy">Pilih 1 angka rahasia antara ${r.min}–${r.max}.</p>${numberCells(input,true)}${keypad()}<div class="button-row"><button class="primary-btn big" id="lockSecretBtn" ${validSecretInput()?'':'disabled'}>🔒 LOCK ANGKA</button></div></div></section>`}
function validSecretInput(){if(!input.length)return false;const n=Number(input),r=game.range;if(n<r.min||n>r.max)return false;if(game.secretIndex===1&&game.secrets[0]===n)return false;return true}
function passTurn(){const a=game.turn;return `<section class="panel"><div class="pass-screen"><div class="big-emoji">😼📱</div><div class="round-pill">ROUND ${game.round}</div><div class="player-name">Giliran ${esc(game.names[a])}</div><p class="hero-copy">Berikan device ke ${esc(game.names[a])}. Jangan biarkan lawan melihat history tebakan.</p><button class="primary-btn big" id="openTurnBtn">Saya ${esc(game.names[a])} → mulai menebak</button></div></section>`}
function rangeHint(player){const hist=game.history[player],r=game.range;let lo=r.min,hi=r.max;for(const h of hist){if(h.result==='higher')lo=Math.max(lo,h.guess+1);if(h.result==='lower')hi=Math.min(hi,h.guess-1)}return `<div class="range-hint">Kemungkinan angka lawan (dari tebakanmu sendiri): <b>${lo} – ${hi}</b></div>`}
function historyMarkup(player){const hist=[...game.history[player]].reverse();if(!hist.length)return `<div class="note">Belum ada attempt.</div>`;return `<div class="history">${hist.map(h=>`<div class="history-row"><div class="history-num">${h.guess}</div><span class="badge ${h.result}">${h.result==='exact'?'🎯 TEPAT':h.result==='higher'?'🔼 Lebih tinggi':'🔽 Lebih rendah'}</span><div class="history-meta">Round ${h.round}</div></div>`).join('')}</div>`}
function turnScreen(){const a=game.turn,b=1-a,r=game.range;return `<section class="panel"><div class="turn-screen"><div class="round-pill">ROUND ${game.round} • ${esc(game.names[a])} menebak ${esc(game.names[b])}</div><div class="score-grid"><div class="score-card active"><b>${esc(game.names[a])}</b><span>${game.history[a].length} attempts</span></div><div class="score-card"><b>${esc(game.names[b])}</b><span>${game.history[b].length} attempts</span></div></div><div class="range-row"><span class="range-chip">Rentang: ${r.min} – ${r.max}</span></div><div class="known-label">TEBAKAN SEKARANG</div>${numberCells(input)}${keypad()}<div class="button-row"><button class="primary-btn big" id="guessBtn" ${validGuessInput()?'':'disabled'}>ENTER GUESS</button></div>${rangeHint(a)}<div class="history-wrap"><div class="history-title"><b>History ${esc(game.names[a])}</b><span class="eyebrow">PRIVAT</span></div>${historyMarkup(a)}</div></div></section>`}
function validGuessInput(){if(!input.length)return false;const n=Number(input),r=game.range;return n>=r.min&&n<=r.max}
function evaluate(guess,secret){if(guess===secret)return{result:'exact'};return{result:guess<secret?'higher':'lower'}}
function feedbackScreen(){const f=game.lastFeedback,a=f.player,b=1-a;const label=f.result==='exact'?'🎯 TEPAT!':f.result==='higher'?'🔼 LEBIH TINGGI':'🔽 LEBIH RENDAH';return `<section class="panel"><div class="result-screen"><div class="round-pill">ROUND ${f.round}</div><div class="eyebrow">TEBAKAN ${esc(game.names[a])}: ${f.guess}</div><div class="big-result ${f.result}">${label}</div>${f.result==='exact'?`<h2>🔓 KETEBAK!</h2><p class="hero-copy">${game.pendingTieCheck?`${esc(game.names[b])} tetap mendapat kesempatan pada ronde yang sama.`:'Tunggu hasil akhir ronde.'}</p>`:`<p class="hero-copy">Angka lawan ${f.result==='higher'?'lebih tinggi':'lebih rendah'} dari ${f.guess}. Coba lagi giliran berikutnya.</p>`}<button class="primary-btn big" id="continueBtn">${game.phaseAfterFeedback==='final'?'🏆 Lihat Hasil':'📱 Pass Device'}</button></div></section>`}
function finalScreen(){const w=game.winner;let title=w==='draw'?'🤝 SERI!':`🏆 ${esc(game.names[w])} MENANG!`;let sub=w==='draw'?`Keduanya menebak tepat pada Round ${game.round}.`:`${esc(game.names[w])} menebak tepat lebih dulu dalam ronde yang seimbang.`;return `<section class="panel"><div class="result-screen"><div class="eyebrow">FINAL RESULT</div><div class="win-title">${title}</div><p class="hero-copy">${sub}</p><div class="secret-reveal">${[0,1].map(i=>`<div class="secret-card"><b>${esc(game.names[i])}</b><div class="num-big">${game.secrets[i]}</div><span class="eyebrow">ANGKA RAHASIA</span></div>`).join('')}</div><div class="button-row"><button class="primary-btn big" id="rematchBtn">🔁 Rematch</button><button class="secondary-btn" id="homeBtn">🏠 Beranda</button></div></div></section>`}
function render(){E.app.innerHTML=!game?home():game.phase==='setup'?setup():game.phase==='passSecret'?passSecret():game.phase==='secret'?secretEntry():game.phase==='passTurn'?passTurn():game.phase==='turn'?turnScreen():game.phase==='feedback'?feedbackScreen():finalScreen();bind()}
function bind(){
 $('#setupBtn')?.addEventListener('click',()=>{game={phase:'setup'};render()});
 $('#cancelBtn')?.addEventListener('click',()=>{game=null;render()});
 document.querySelectorAll('[data-preset]').forEach(btn=>btn.onclick=()=>{prefs.presetIdx=Number(btn.dataset.preset);savePrefs();render()});
 $('#customMin')?.addEventListener('change',()=>{prefs.customMin=Number($('#customMin').value)||1;savePrefs()});
 $('#customMax')?.addEventListener('change',()=>{prefs.customMax=Number($('#customMax').value)||100;savePrefs()});
 $('#beginBtn')?.addEventListener('click',()=>{let a=$('#nameA').value.trim()||'Player A',b=$('#nameB').value.trim()||'Player B';prefs.names=[a,b];let range;if(prefs.presetIdx===-1){let mn=Number($('#customMin')?.value)||1,mx=Number($('#customMax')?.value)||100;if(mn>=mx){mn=1;mx=100}range={min:mn,max:mx}}else{const pr=PRESETS[prefs.presetIdx];range={min:pr.min,max:pr.max}}savePrefs();game={phase:'passSecret',names:[a,b],range,secrets:[null,null],secretIndex:0,history:[[],[]],turn:0,round:1,solvedRound:[null,null],winner:null};input='';render()});
 $('#enterSecretBtn')?.addEventListener('click',()=>{input='';game.phase='secret';render()});
 document.querySelectorAll('[data-digit]').forEach(btn=>btn.onclick=()=>{const len=maxDigits();if(input.length<len){input+=btn.dataset.digit;beep(560,.03);render()}});
 document.querySelector('[data-back]')?.addEventListener('click',()=>{input=input.slice(0,-1);render()});
 document.querySelector('[data-clear]')?.addEventListener('click',()=>{input='';render()});
 $('#lockSecretBtn')?.addEventListener('click',()=>{if(!validSecretInput())return;game.secrets[game.secretIndex]=Number(input);input='';if(game.secretIndex===0){game.secretIndex=1;game.phase='passSecret'}else{game.phase='passTurn';game.turn=0}beep(760,.07);render()});
 $('#openTurnBtn')?.addEventListener('click',()=>{input='';game.phase='turn';render()});
 $('#guessBtn')?.addEventListener('click',()=>{if(!validGuessInput())return;const a=game.turn,b=1-a,guessNum=Number(input),r=evaluate(guessNum,game.secrets[b]);const rec={guess:guessNum,result:r.result,round:game.round};game.history[a].push(rec);if(r.result==='exact')game.solvedRound[a]=game.round;game.lastFeedback={...rec,player:a};input='';
   if(a===0){game.pendingTieCheck=r.result==='exact';game.turn=1;game.phaseAfterFeedback='passTurn';}
   else{const aSolved=game.solvedRound[0]===game.round,bSolved=game.solvedRound[1]===game.round;if(aSolved||bSolved){game.winner=aSolved&&bSolved?'draw':(aSolved?0:1);game.phaseAfterFeedback='final'}else{game.round++;game.turn=0;game.phaseAfterFeedback='passTurn'}game.pendingTieCheck=false}game.phase='feedback';beep(r.result==='exact'?900:500,.08);render()});
 $('#continueBtn')?.addEventListener('click',()=>{game.phase=game.phaseAfterFeedback;render()});
 $('#rematchBtn')?.addEventListener('click',()=>{const names=[...game.names],range=game.range;game={phase:'passSecret',names,range,secrets:[null,null],secretIndex:0,history:[[],[]],turn:0,round:1,solvedRound:[null,null],winner:null};input='';render()});
 $('#homeBtn')?.addEventListener('click',()=>{game=null;render()});
}
E.theme.onclick=()=>{prefs.theme=prefs.theme==='dark'?'light':'dark';savePrefs();applyTheme()};E.sound.onclick=()=>{prefs.sound=!prefs.sound;savePrefs();applyTheme();beep(700,.04)};E.reset.onclick=()=>{if(confirm('Mulai game baru? Progress sekarang akan hilang.')){game=null;input='';render()}};applyTheme();render();
