window.MIAU_SEED = {
  players: [
    {id:'P001',name:'Oren'},
    {id:'P002',name:'Tux'},
    {id:'P003',name:'Mochi'},
    {id:'P004',name:'Cimi'}
  ],
  actions: [
    {id:'A001',phrase:'MIAU!',action:'Buat telinga kucing dengan dua tangan.',icon:'🐱',color:'orange',difficulty:'easy'},
    {id:'A002',phrase:'BOING!',action:'Dorong kedua telapak tangan ke atas.',icon:'👐',color:'blue',difficulty:'easy'},
    {id:'A003',phrase:'CUSS!',action:'Tunjuk lurus ke depan seperti koboi.',icon:'👉',color:'green',difficulty:'easy'},
    {id:'A004',phrase:'NYAM!',action:'Usap perut satu kali.',icon:'😋',color:'purple',difficulty:'easy'},
    {id:'A005',phrase:'PING!',action:'Sentuh ujung hidung dengan satu jari.',icon:'👃',color:'orange',difficulty:'easy'},
    {id:'A006',phrase:'WUSH!',action:'Sapukan satu tangan melewati kepala.',icon:'💨',color:'blue',difficulty:'easy'},
    {id:'A007',phrase:'GAS!',action:'Angkat dua jempol.',icon:'👍',color:'green',difficulty:'easy'},
    {id:'A008',phrase:'BONK!',action:'Ketuk pelan kepalan ke telapak sendiri.',icon:'👊',color:'purple',difficulty:'easy'},
    {id:'A009',phrase:'YAHOO!',action:'Lambaikan satu tangan di atas kepala.',icon:'🤠',color:'orange',difficulty:'easy'},
    {id:'A010',phrase:'BEEP!',action:'Tekan tombol khayalan di udara.',icon:'🔘',color:'blue',difficulty:'easy'},
    {id:'A011',phrase:'HEH!',action:'Silangkan tangan di dada.',icon:'😼',color:'green',difficulty:'medium'},
    {id:'A012',phrase:'PLOP!',action:'Tepuk kedua paha sekali.',icon:'🫳',color:'purple',difficulty:'easy'},
    {id:'A013',phrase:'BRRR!',action:'Goyangkan kedua bahu cepat.',icon:'🥶',color:'orange',difficulty:'medium'},
    {id:'A014',phrase:'CIAO!',action:'Salam dua jari dari dahi.',icon:'✌️',color:'blue',difficulty:'medium'},
    {id:'A015',phrase:'POP!',action:'Buka tangan dari kepalan menjadi lima jari.',icon:'🖐️',color:'green',difficulty:'medium'},
    {id:'A016',phrase:'SST!',action:'Telunjuk di depan bibir.',icon:'🤫',color:'purple',difficulty:'easy'},
    {id:'A017',phrase:'MEONG!',action:'Buat kumis dengan dua telunjuk.',icon:'😺',color:'orange',difficulty:'medium'},
    {id:'A018',phrase:'WOI!',action:'Letakkan tangan di samping telinga.',icon:'👂',color:'blue',difficulty:'medium'},
    {id:'A019',phrase:'JRENG!',action:'Pura-pura petik gitar sekali.',icon:'🎸',color:'green',difficulty:'medium'},
    {id:'A020',phrase:'TING!',action:'Gambar lingkaran kecil di udara.',icon:'⭕',color:'purple',difficulty:'medium'},
    {id:'A021',phrase:'HUP!',action:'Angkat satu lutut sedikit dari posisi duduk.',icon:'🦵',color:'orange',difficulty:'hard'},
    {id:'A022',phrase:'BAM!',action:'Kedua telapak saling bertemu sekali.',icon:'👏',color:'blue',difficulty:'medium'},
    {id:'A023',phrase:'EH?',action:'Miringkan kepala dan angkat satu telapak.',icon:'🤨',color:'green',difficulty:'medium'},
    {id:'A024',phrase:'FUIH!',action:'Kipas wajah dengan satu tangan.',icon:'🥵',color:'purple',difficulty:'medium'},
    {id:'A025',phrase:'ZIP!',action:'Tarik jari melintang di depan mulut.',icon:'🤐',color:'orange',difficulty:'hard'},
    {id:'A026',phrase:'HAH!',action:'Kedua tangan di pipi.',icon:'😱',color:'blue',difficulty:'easy'},
    {id:'A027',phrase:'CUKUP!',action:'Buat tanda stop dengan satu telapak.',icon:'✋',color:'green',difficulty:'easy'},
    {id:'A028',phrase:'SKRRT!',action:'Putar dua tangan seperti setir.',icon:'🏎️',color:'purple',difficulty:'hard'},
    {id:'A029',phrase:'BLUP!',action:'Gembungkan pipi lalu tunjuk ke bawah.',icon:'🐟',color:'orange',difficulty:'hard'},
    {id:'A030',phrase:'TADA!',action:'Rentangkan kedua telapak ke samping.',icon:'✨',color:'blue',difficulty:'easy'}
  ],
  modifiers: [
    {id:'M001',title:'ULANG LAGI',effect:'Semua Action Card warna target dilakukan dua kali berturut-turut.',difficulty:'medium',targetMode:'color',tag:'×2'},
    {id:'M002',title:'MODE BISIK',effect:'Ucapkan phrase pada warna target dengan suara berbisik.',difficulty:'easy',targetMode:'color',tag:'🤫'},
    {id:'M003',title:'ROBOT',effect:'Phrase pada warna target harus diucapkan seperti robot.',difficulty:'easy',targetMode:'color',tag:'🤖'},
    {id:'M004',title:'SLOW-MO',effect:'Gerakan pada warna target harus dilakukan super lambat tanpa kehilangan beat.',difficulty:'medium',targetMode:'color',tag:'🐌'},
    {id:'M005',title:'SUARA BOS',effect:'Phrase pada warna target harus diucapkan dengan suara lantang.',difficulty:'easy',targetMode:'color',tag:'📣'},
    {id:'M006',title:'TANGAN KIRI',effect:'Jika aksi bisa dilakukan satu tangan, warna target wajib memakai tangan kiri.',difficulty:'medium',targetMode:'color',tag:'⬅️'},
    {id:'M007',title:'MINI MODE',effect:'Gerakan warna target dibuat sekecil mungkin tapi tetap dikenali.',difficulty:'medium',targetMode:'color',tag:'🤏'},
    {id:'M008',title:'BIG MODE',effect:'Gerakan warna target dibuat lebih besar dan dramatis.',difficulty:'medium',targetMode:'color',tag:'💥'},
    {id:'M009',title:'TANPA KATA',effect:'Action Card target dilakukan gerakannya saja; jangan ucapkan phrase.',difficulty:'hard',targetMode:'action',tag:'🔇'},
    {id:'M010',title:'KATA SAJA',effect:'Action Card target diucapkan phrase-nya saja; jangan lakukan gerakan.',difficulty:'hard',targetMode:'action',tag:'🗣️'},
    {id:'M011',title:'SEBELUMNYA',effect:'Setelah Action Card target, ulangi phrase kartu tepat sebelumnya.',difficulty:'hard',targetMode:'action',tag:'↩️'},
    {id:'M012',title:'TEPUK BONUS',effect:'Sebelum Action Card target, tepuk tangan sekali.',difficulty:'medium',targetMode:'action',tag:'👏'},
    {id:'M013',title:'MUKA DATAR',effect:'Saat melakukan Action Card target, usahakan ekspresi wajah tetap datar.',difficulty:'medium',targetMode:'action',tag:'😐'},
    {id:'M014',title:'ECHO',effect:'Setelah phrase Action Card target, ucapkan satu kali lagi lebih pelan.',difficulty:'hard',targetMode:'action',tag:'🔁'},
    {id:'M015',title:'SEMUA MIAU',effect:'Setelah setiap action selesai, tambahkan satu “miau” pendek.',difficulty:'hard',targetMode:'all',tag:'🐱'}
  ],
  attacks: [
    {id:'X001',title:'SATU TANGAN',effect:'Target hanya boleh memakai satu tangan untuk semua action yang memungkinkan.',difficulty:'medium',targetMode:'either',tag:'☝️'},
    {id:'X002',title:'SIKU NEMPEL',effect:'Target pemain menjaga siku dekat sisi tubuh saat melakukan action.',difficulty:'medium',targetMode:'player',tag:'🦖'},
    {id:'X003',title:'TOPI KHAYALAN',effect:'Target pemain menjaga satu tangan di atas kepala selama action.',difficulty:'hard',targetMode:'player',tag:'🎩'},
    {id:'X004',title:'MUKA SERIUS',effect:'Target pemain tidak boleh sengaja tersenyum saat melakukan action.',difficulty:'medium',targetMode:'player',tag:'😾'},
    {id:'X005',title:'JEMPOL NAIK',effect:'Saat Action Card target dilakukan, tangan bebas harus membentuk jempol naik.',difficulty:'hard',targetMode:'action',tag:'👍'},
    {id:'X006',title:'SATU MATA',effect:'Saat Action Card target dilakukan, pemain mengedipkan satu mata.',difficulty:'medium',targetMode:'action',tag:'😉'},
    {id:'X007',title:'KEPALA MIRING',effect:'Target pemain memiringkan kepala sedikit setiap melakukan action.',difficulty:'medium',targetMode:'player',tag:'🙃'},
    {id:'X008',title:'JARI KELINGKING',effect:'Saat Action Card target dilakukan, angkat kelingking tangan bebas.',difficulty:'hard',targetMode:'action',tag:'🤙'},
    {id:'X009',title:'SUARA MINI',effect:'Target pemain mengucapkan semua phrase dengan volume lebih kecil.',difficulty:'medium',targetMode:'player',tag:'🔉'},
    {id:'X010',title:'DRAMA',effect:'Saat Action Card target dilakukan, buat gerakannya sedikit lebih teatrikal.',difficulty:'easy',targetMode:'action',tag:'🎭'}
  ]
};
