const STORAGE_KEY='miau-secret-word-duel-v1';
const $=s=>document.querySelector(s);
const E={
  app:$('#app'),themeBtn:$('#themeBtn'),soundBtn:$('#soundBtn'),manageBtn:$('#manageBtn'),
  manageDialog:$('#manageDialog'),manageContent:$('#manageContent'),
  formDialog:$('#formDialog'),crudForm:$('#crudForm'),formEyebrow:$('#formEyebrow'),formTitle:$('#formTitle'),formFields:$('#formFields'),
  formCloseBtn:$('#formCloseBtn'),formCancelBtn:$('#formCancelBtn'),toast:$('#toast')
};
let db=loadDB(),game=null,manageTab='players',editing=null,audioCtx=null,cardDeck=[],wordVisible=false,wordSeen=false;

function clone(v){return JSON.parse(JSON.stringify(v))}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function normalize(v=''){return String(v).toLocaleLowerCase('id-ID').trim().replace(/[.,!?;:'"`()\[\]{}]/g,'').replace(/\s+/g,' ')}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(db))}
function loadDB(){
  try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY));if(Array.isArray(x?.players)&&Array.isArray(x?.cards))return x}catch{}
  return {players:clone(SEED_PLAYERS),cards:clone(SEED_CARDS),theme:'light',sound:true,playerSeq:5,cardSeq:151}
}
function toast(m){E.toast.textContent=m;E.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.classList.remove('show'),1700)}
function beep(f=650,d=.06){if(!db.sound)return;try{audioCtx||=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=f;g.gain.setValueAtTime(.05,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch{}}
function applyTheme(){document.documentElement.dataset.theme=db.theme;E.themeBtn.textContent=db.theme==='dark'?'☀️':'🌙';E.soundBtn.textContent=db.sound?'🔊':'🔇'}
function p(id){return db.players.find(x=>x.id===id)}
function c(id){return db.cards.find(x=>x.id===id)}
function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function categories(){return [...new Set(db.cards.map(x=>x.category))].sort((a,b)=>a.localeCompare(b,'id'))}
function getNextCard(filter){
  const eligible=db.cards.filter(x=>filter==='Semua'||x.category===filter).map(x=>x.id);
  if(!eligible.length)return null;
  const set=new Set(eligible);cardDeck=cardDeck.filter(id=>set.has(id));
  if(!cardDeck.length)cardDeck=shuffle(eligible);
  return cardDeck.shift();
}
function opponent(id){return game.players.find(x=>x!==id)}
function cycleOrder(){return game.cycle%2===1?[...game.players]:[...game.players].reverse()}
function guessOrder(){return game.cycle%2===1?[...game.players].reverse():[...game.players]}
function scoreCard(id){return `<div class="score-card"><b>${esc(p(id)?.name||id)}</b><div class="score-number">${game.scores[id]}</div><span>Target ${game.targetScore}</span></div>`}
function scores(){return `<div class="score-grid">${game.players.map(scoreCard).join('')}</div>`}
function progress(){const phase=game.phase;const active=phase.startsWith('word')?'word':phase.startsWith('clue')||phase==='publicClues'?'clue':phase.startsWith('guess')||phase==='resolve'?'guess':'result';const a=[['word','1. Secret'],['clue','2. Clue'],['guess','3. Guess'],['result','4. Resolve']];return `<div class="progress">${a.map(([id,t])=>`<div class="progress-step ${active===id?'active':''}">${t}</div>`).join('')}</div>`}
function shell(content){const card=c(game.cardId);return `<div class="game-head"><div><div class="eyebrow">MATCH • ROUND ${game.round}</div><div class="round-pill">Cycle ${game.cycle} / ${game.maxCycles}</div></div><div class="category-pill">${esc(card?.category||'—')} • ${esc(card?.difficulty||'—')}</div></div>${scores()}<section class="panel">${progress()}${content}</section>`}

function home(){return `<section class="hero"><div class="panel hero-main"><div class="eyebrow">ORIGINAL 2-PLAYER WORD DUEL</div><div class="hero-title">Clue kecil.<br>Tebak besar.</div><p class="hero-copy">Kalian mendapat dua kata yang saling berhubungan tetapi berbeda. Setiap cycle, keduanya memberi <b>satu clue kata</b> tentang kata sendiri, lalu menebak kata lawan secara rahasia. Tebakan dibuka bersamaan.</p><div class="button-row"><button class="primary-btn big" id="setupBtn">😼 Mulai Duel</button><button class="secondary-btn big" id="homeManageBtn">⚙️ CRUD</button></div><div class="note">Contoh: A mendapat <b>Kucing</b>, B mendapat <b>Harimau</b>. A mungkin clue “rumahan”, B mungkin clue “belang”. Jangan terlalu jelas—lawan sedang memburu katamu.</div></div><div class="panel"><div class="eyebrow">DATABASE</div><div class="stat-grid"><div class="stat"><b>${db.cards.length}</b><span>Pasangan kata</span></div><div class="stat"><b>${db.players.length}</b><span>Pemain tersimpan</span></div><div class="stat"><b>1 kata</b><span>Maksimum tiap clue</span></div><div class="stat"><b>Simultan</b><span>Resolve tebakan</span></div></div></div></section>`}

function setupScreen(){const cats=categories();return `<section class="panel"><div class="eyebrow">SETUP MATCH</div><h2>Pilih tepat dua pemain.</h2><div class="player-select">${db.players.map((x,i)=>`<label class="player-check"><input type="checkbox" data-player="${x.id}" ${i<2?'checked':''}><span>${esc(x.name)}</span></label>`).join('')}</div><div class="setup-grid"><label class="field">Kategori<select id="categoryFilter"><option>Semua</option>${cats.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label class="field">Target skor<select id="targetScore"><option>3</option><option selected>5</option><option>7</option></select></label><label class="field">Max cycle/round<select id="maxCycles"><option>4</option><option selected>6</option><option>8</option></select></label></div><div class="button-row"><button class="primary-btn big" id="startMatchBtn">🔐 Mulai Match</button><button class="secondary-btn" id="cancelSetupBtn">Batal</button></div></section>`}
function startMatch(){const players=[...document.querySelectorAll('[data-player]:checked')].map(x=>x.dataset.player);if(players.length!==2)return toast('Pilih tepat 2 pemain.');game={phase:'',players,scores:{[players[0]]:0,[players[1]]:0},targetScore:Number($('#targetScore').value),maxCycles:Number($('#maxCycles').value),filter:$('#categoryFilter').value,round:0};startRound()}
function startRound(){const cardId=getNextCard(game.filter);if(!cardId)return toast('Tidak ada pasangan kata di kategori ini.');game.round++;game.cardId=cardId;game.cycle=1;game.wordIndex=0;game.clueIndex=0;game.guessIndex=0;game.clueHistory=[];game.pendingClues={};game.pendingGuesses={};game.resolution=null;const card=c(cardId);const swap=Math.random()<.5;game.words=swap?{[game.players[0]]:card.wordB,[game.players[1]]:card.wordA}:{[game.players[0]]:card.wordA,[game.players[1]]:card.wordB};game.phase='wordPass';wordVisible=false;wordSeen=false;beep(720,.07);render()}
function currentWordPlayer(){return game.players[game.wordIndex]}
function wordPass(){const id=currentWordPlayer();return shell(`<div class="center-screen"><div class="big-emoji">🔒💬</div><div class="eyebrow">SECRET WORD</div><div class="big-name">${esc(p(id)?.name||id)}</div><p class="hero-copy">Pastikan hanya pemain ini yang melihat layar.</p><button id="openWordBtn" class="primary-btn big">Saya ${esc(p(id)?.name||id)} → lanjut</button></div>`)}
function wordView(){const id=currentWordPlayer(),word=game.words[id];return shell(`<div class="center-screen"><div class="secret-box"><div class="eyebrow">KATAMU</div><div class="${wordVisible?'secret-word':'secret-hidden'}">${wordVisible?esc(word):'••••••••'}</div><p class="hero-copy">${wordVisible?'Ingat kata ini. Lawan mendapat kata lain yang masih berhubungan.':'Tahan tombol untuk melihat.'}</p></div><button id="holdWordBtn" class="primary-btn big hold-btn">👆 TAHAN UNTUK LIHAT</button><button id="wordDoneBtn" class="secondary-btn big" ${wordSeen?'':'disabled'}>✅ Saya sudah ingat</button></div>`)}
function wordDone(){wordVisible=false;wordSeen=false;game.wordIndex++;if(game.wordIndex>=2){game.phase='cluePass';game.clueIndex=0}else game.phase='wordPass';render()}

function currentCluePlayer(){return cycleOrder()[game.clueIndex]}
function cluePass(){const id=currentCluePlayer();return shell(`<div class="center-screen"><div class="big-emoji">💡🔒</div><div class="eyebrow">CLUE ${game.cycle}</div><div class="big-name">${esc(p(id)?.name||id)}</div><p class="hero-copy">Masukkan satu kata clue tentang <b>katamu sendiri</b>. Clue pemain pertama tetap tersembunyi sampai keduanya lock.</p><button id="openClueBtn" class="primary-btn big">✍️ Masukkan Clue</button></div>`)}
function clueEntry(){const id=currentCluePlayer(),own=game.words[id];return shell(`<div class="center-screen"><div class="entry-box"><div class="eyebrow">${esc(p(id)?.name||id)} • CLUE ${game.cycle}</div><h2>Satu kata. Tentang katamu.</h2><input id="clueInput" maxlength="24" autocomplete="off" autocapitalize="off" placeholder="contoh: belang"><div id="clueWarning" class="rule-warning"></div></div><div class="note">Tidak boleh memakai kata rahasia atau salah satu kata penyusunnya. Clue yang pernah kamu pakai ronde ini juga tidak boleh diulang.</div><div class="button-row"><button id="lockClueBtn" class="primary-btn big">🔒 Lock Clue</button></div></div>`)}
function validateClue(id,value){const v=value.trim();if(!v)return 'Clue kosong.';if(/\s/.test(v))return 'Clue harus satu kata saja.';const n=normalize(v);const secret=normalize(game.words[id]);const secretParts=secret.split(/[^\p{L}\p{N}]+/u).filter(Boolean);if(n===secret||secretParts.includes(n))return 'Clue tidak boleh memakai kata rahasia atau bagiannya.';const used=game.clueHistory.map(h=>normalize(h.clues[id]||''));if(used.includes(n))return 'Clue ini sudah pernah kamu pakai.';return ''}
function lockClue(){const id=currentCluePlayer(),input=$('#clueInput'),warning=$('#clueWarning'),value=input.value.trim(),err=validateClue(id,value);if(err){warning.textContent=err;beep(180,.05);return}game.pendingClues[id]=value;game.clueIndex++;if(game.clueIndex>=2){game.clueHistory.push({cycle:game.cycle,clues:{...game.pendingClues}});game.phase='publicClues'}else game.phase='cluePass';beep(650,.05);render()}
function publicClues(){const latest=game.clueHistory.at(-1);return shell(`<div class="public-board"><div class="cycle-title"><div class="eyebrow">CLUES LOCKED</div><h2>Kedua clue sekarang publik.</h2></div><div class="clue-grid">${game.players.map(id=>`<div class="clue-card"><div class="who">${esc(p(id)?.name||id)}</div><div class="clue-word">${esc(latest.clues[id])}</div></div>`).join('')}</div>${historyMarkup()}<div class="button-row" style="justify-content:center;margin-top:14px"><button id="startGuessBtn" class="primary-btn big">🧠 Mulai Tebakan Rahasia</button></div></div>`)}
function historyMarkup(){if(game.clueHistory.length<=1)return '';return `<div class="history"><div class="eyebrow">HISTORY CLUE</div>${game.clueHistory.map(h=>`<div class="history-row"><b>C${h.cycle}</b><div class="history-clue">${esc(p(game.players[0])?.name)}: ${esc(h.clues[game.players[0]])}</div><div class="history-clue">${esc(p(game.players[1])?.name)}: ${esc(h.clues[game.players[1]])}</div></div>`).join('')}</div>`}

function currentGuessPlayer(){return guessOrder()[game.guessIndex]}
function guessPass(){const id=currentGuessPlayer(),opp=opponent(id);return shell(`<div class="center-screen"><div class="big-emoji">🧠🔒</div><div class="eyebrow">PRIVATE GUESS</div><div class="big-name">${esc(p(id)?.name||id)}</div><p class="hero-copy">Sekarang tebak kata milik <b>${esc(p(opp)?.name||opp)}</b>, atau PASS. Tebakanmu tidak dibuka sampai lawan juga lock.</p><button id="openGuessBtn" class="primary-btn big">🎯 Masukkan Tebakan</button></div>`)}
function guessEntry(){const id=currentGuessPlayer(),opp=opponent(id);return shell(`<div class="center-screen"><div class="entry-box"><div class="eyebrow">${esc(p(id)?.name||id)} → ${esc(p(opp)?.name||opp)}</div><h2>Apa kata lawan?</h2><input id="guessInput" maxlength="50" autocomplete="off" placeholder="ketik tebakan"><div class="rule-warning">Boleh multi-kata. Kalau belum yakin, PASS.</div></div><div class="button-row"><button id="lockGuessBtn" class="primary-btn big">🔒 Lock Guess</button><button id="passGuessBtn" class="secondary-btn big">PASS</button></div></div>`)}
function lockGuess(pass=false){const id=currentGuessPlayer(),value=pass?'':$('#guessInput').value.trim();if(!pass&&!value)return toast('Ketik tebakan atau pilih PASS.');game.pendingGuesses[id]=value;game.guessIndex++;if(game.guessIndex>=2){calculateResolution();game.phase='resolve'}else game.phase='guessPass';beep(620,.05);render()}
function calculateResolution(){const result={};for(const id of game.players){const opp=opponent(id),guess=game.pendingGuesses[id]||'';result[id]={guess,correct:!!guess&&normalize(guess)===normalize(game.words[opp])}}const correct=game.players.filter(id=>result[id].correct);let outcome='none',winner=null;if(correct.length===2)outcome='both';else if(correct.length===1){outcome='one';winner=correct[0];game.scores[winner]++}else if(game.cycle>=game.maxCycles)outcome='timeout';game.resolution={result,outcome,winner}}
function resolveScreen(){const r=game.resolution;const roundOver=r.outcome!=='none';return shell(`<div class="center-screen"><div class="eyebrow">SIMULTANEOUS REVEAL</div><h2>${roundOver?'Hasil ronde':'Belum ada yang memecahkan kata.'}</h2><div class="guess-grid">${game.players.map(id=>{const opp=opponent(id),x=r.result[id];return `<div class="guess-result ${x.correct?'correct':x.guess?'wrong':''}"><div class="eyebrow">${esc(p(id)?.name)} menebak ${esc(p(opp)?.name)}</div><div class="guess-text">${x.guess?esc(x.guess):'PASS'}</div><div>${x.correct?'✅ BENAR':x.guess?'❌ BELUM':'—'}</div></div>`}).join('')}</div>${resolveMessage()}<div class="button-row">${roundOver?`<button id="roundDoneBtn" class="primary-btn big">${matchWinner()?'🏆 Hasil Match':'➡️ Round Berikut'}</button>`:`<button id="nextCycleBtn" class="primary-btn big">💡 Cycle ${game.cycle+1}</button>`}</div></div>`)}
function resolveMessage(){const r=game.resolution;if(r.outcome==='one')return `<div class="result-title">🏆 ${esc(p(r.winner)?.name)} +1</div><p class="hero-copy">Berhasil memecahkan kata lawan sendirian pada cycle ${game.cycle}.</p>`;if(r.outcome==='both')return `<div class="result-title">🤝 DRAW</div><p class="hero-copy">Keduanya benar pada cycle yang sama. Tidak ada poin ronde ini.</p>`;if(r.outcome==='timeout')return `<div class="result-title">🔒 STALEMATE</div><p class="hero-copy">Tidak ada yang berhasil dalam ${game.maxCycles} cycle. Tidak ada poin.</p>`;return `<div class="feedback">0 / 2 correct</div><p class="hero-copy">Kalian sekarang punya lebih banyak clue. Jangan bocorkan kata sendiri terlalu cepat.</p>`}
function matchWinner(){return game.players.find(id=>game.scores[id]>=game.targetScore)||null}
function nextCycle(){game.cycle++;game.pendingClues={};game.pendingGuesses={};game.clueIndex=0;game.guessIndex=0;game.resolution=null;game.phase='cluePass';render()}
function roundDone(){const winner=matchWinner();if(winner){game.phase='matchEnd';render()}else startRound()}
function matchEnd(){const winner=matchWinner();return `<section class="panel"><div class="center-screen"><div class="big-emoji">🏆😼</div><div class="eyebrow">MATCH SELESAI</div><div class="result-title">${esc(p(winner)?.name)} MENANG</div>${scores()}<div class="word-pair"><div class="word-card"><div class="eyebrow">PLAYER 1</div><b>${esc(p(game.players[0])?.name)}</b></div><div class="word-card"><div class="eyebrow">PLAYER 2</div><b>${esc(p(game.players[1])?.name)}</b></div></div><div class="button-row"><button id="rematchBtn" class="primary-btn big">🔁 Rematch</button><button id="endMatchBtn" class="secondary-btn">🏠 Beranda</button></div></div></section>`}

function render(){if(!game){E.app.innerHTML=home();bind();return}if(game.phase==='setup'){E.app.innerHTML=setupScreen();bind();return}if(game.phase==='matchEnd'){E.app.innerHTML=matchEnd();bind();return}E.app.innerHTML=game.phase==='wordPass'?wordPass():game.phase==='wordView'?wordView():game.phase==='cluePass'?cluePass():game.phase==='clueEntry'?clueEntry():game.phase==='publicClues'?publicClues():game.phase==='guessPass'?guessPass():game.phase==='guessEntry'?guessEntry():resolveScreen();bind()}
function bind(){
  $('#setupBtn')?.addEventListener('click',()=>{game={phase:'setup'};render()});
  $('#homeManageBtn')?.addEventListener('click',()=>{renderManage();E.manageDialog.showModal()});
  $('#startMatchBtn')?.addEventListener('click',startMatch);$('#cancelSetupBtn')?.addEventListener('click',()=>{game=null;render()});
  $('#openWordBtn')?.addEventListener('click',()=>{game.phase='wordView';wordSeen=false;render()});
  const hold=$('#holdWordBtn');if(hold){hold.addEventListener('pointerdown',e=>{e.preventDefault();wordVisible=true;wordSeen=true;beep(820,.04);render()});const hide=()=>{if(wordVisible){wordVisible=false;render()}};hold.addEventListener('pointerup',hide);hold.addEventListener('pointercancel',hide);hold.addEventListener('pointerleave',hide)}
  $('#wordDoneBtn')?.addEventListener('click',wordDone);
  $('#openClueBtn')?.addEventListener('click',()=>{game.phase='clueEntry';render();setTimeout(()=>$('#clueInput')?.focus(),30)});$('#lockClueBtn')?.addEventListener('click',lockClue);
  $('#startGuessBtn')?.addEventListener('click',()=>{game.guessIndex=0;game.pendingGuesses={};game.phase='guessPass';render()});
  $('#openGuessBtn')?.addEventListener('click',()=>{game.phase='guessEntry';render();setTimeout(()=>$('#guessInput')?.focus(),30)});$('#lockGuessBtn')?.addEventListener('click',()=>lockGuess(false));$('#passGuessBtn')?.addEventListener('click',()=>lockGuess(true));
  $('#nextCycleBtn')?.addEventListener('click',nextCycle);$('#roundDoneBtn')?.addEventListener('click',roundDone);$('#rematchBtn')?.addEventListener('click',()=>{const keep={players:[...game.players],targetScore:game.targetScore,maxCycles:game.maxCycles,filter:game.filter};game={phase:'',players:keep.players,scores:{[keep.players[0]]:0,[keep.players[1]]:0},targetScore:keep.targetScore,maxCycles:keep.maxCycles,filter:keep.filter,round:0};startRound()});$('#endMatchBtn')?.addEventListener('click',()=>{game=null;render()})
}

function renderManage(q=''){document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===manageTab));if(manageTab==='players')return managePlayers(q);if(manageTab==='cards')return manageCards(q);manageData()}
function managePlayers(q=''){q=q.toLowerCase();const arr=db.players.filter(x=>(x.id+' '+x.name).toLowerCase().includes(q));E.manageContent.innerHTML=`<div class="manage-tools"><input id="manageSearch" class="search" value="${esc(q)}" placeholder="Cari P001 / nama..."><button id="addPlayerBtn" class="primary-btn">+ Pemain</button></div><div class="crud-list">${arr.map(x=>`<div class="crud-row"><div><div class="crud-title">${esc(x.name)}</div><div class="crud-meta">${x.id}</div></div><div class="crud-actions"><button data-ep="${x.id}">✏️</button><button data-dp="${x.id}">🗑️</button></div></div>`).join('')||'<div class="empty">Tidak ada pemain.</div>'}</div>`;$('#manageSearch').oninput=e=>managePlayers(e.target.value);$('#addPlayerBtn').onclick=()=>openPlayer();document.querySelectorAll('[data-ep]').forEach(b=>b.onclick=()=>openPlayer(b.dataset.ep));document.querySelectorAll('[data-dp]').forEach(b=>b.onclick=()=>{if(confirm('Hapus pemain?')){db.players=db.players.filter(x=>x.id!==b.dataset.dp);save();managePlayers();render()}})}
function manageCards(q=''){q=q.toLowerCase();const arr=db.cards.filter(x=>(`${x.id} ${x.category} ${x.wordA} ${x.wordB} ${x.difficulty}`).toLowerCase().includes(q));E.manageContent.innerHTML=`<div class="manage-tools"><input id="manageSearch" class="search" value="${esc(q)}" placeholder="Cari D001 / kategori / kata..."><button id="addCardBtn" class="primary-btn">+ Pasangan</button></div><div class="crud-list">${arr.map(x=>`<div class="crud-row"><div><div class="crud-title">${esc(x.id)} • ${esc(x.wordA)} ↔ ${esc(x.wordB)}</div><div class="crud-meta">${esc(x.category)} • ${esc(x.difficulty)}</div></div><div class="crud-actions"><button data-ec="${x.id}">✏️</button><button data-dc="${x.id}">🗑️</button></div></div>`).join('')||'<div class="empty">Tidak ada pasangan.</div>'}</div>`;$('#manageSearch').oninput=e=>manageCards(e.target.value);$('#addCardBtn').onclick=()=>openCard();document.querySelectorAll('[data-ec]').forEach(b=>b.onclick=()=>openCard(b.dataset.ec));document.querySelectorAll('[data-dc]').forEach(b=>b.onclick=()=>{if(confirm('Hapus pasangan kata?')){db.cards=db.cards.filter(x=>x.id!==b.dataset.dc);cardDeck=[];save();manageCards();render()}})}
function manageData(){E.manageContent.innerHTML=`<div class="panel" style="box-shadow:none"><h3>Backup & Reset</h3><p class="hero-copy">Pemain dan 150 pasangan kata tersimpan di localStorage.</p><div class="button-row"><button id="exportBtn" class="primary-btn">⬇️ Export JSON</button><label class="secondary-btn">⬆️ Import JSON<input id="importInput" type="file" accept=".json,application/json" hidden></label><button id="resetDataBtn" class="danger-btn">♻️ Reset Seed</button></div></div>`;$('#exportBtn').onclick=exportData;$('#importInput').onchange=importData;$('#resetDataBtn').onclick=()=>{if(confirm('Reset pemain dan pasangan kata ke seed awal?')){db={players:clone(SEED_PLAYERS),cards:clone(SEED_CARDS),theme:db.theme,sound:db.sound,playerSeq:5,cardSeq:151};cardDeck=[];save();renderManage();render();toast('Seed dipulihkan.')}}}
function openPlayer(id=null){editing={type:'player',id};const x=id?p(id):null;E.formEyebrow.textContent=x?x.id:'PEMAIN BARU';E.formTitle.textContent=x?'Edit Pemain':'Tambah Pemain';E.formFields.innerHTML=`<label>Nama<input name="name" required maxlength="30" value="${esc(x?.name||'')}"></label>`;E.formDialog.showModal()}
function openCard(id=null){editing={type:'card',id};const x=id?c(id):null;E.formEyebrow.textContent=x?x.id:'PASANGAN BARU';E.formTitle.textContent=x?'Edit Pasangan':'Tambah Pasangan';E.formFields.innerHTML=`<label>Kategori<input name="category" required maxlength="40" value="${esc(x?.category||'Random')}"></label><label>Kata A<input name="wordA" required maxlength="50" value="${esc(x?.wordA||'')}"></label><label>Kata B<input name="wordB" required maxlength="50" value="${esc(x?.wordB||'')}"></label><label>Kesulitan<select name="difficulty">${['Mudah','Sedang','Sulit'].map(d=>`<option ${x?.difficulty===d?'selected':''}>${d}</option>`).join('')}</select></label>`;E.formDialog.showModal()}
E.crudForm.onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(editing.type==='player'){const data={name:String(f.get('name')).trim()};if(editing.id)Object.assign(p(editing.id),data);else db.players.push({id:`P${String(db.playerSeq++).padStart(3,'0')}`,...data})}else{const data={category:String(f.get('category')).trim(),wordA:String(f.get('wordA')).trim(),wordB:String(f.get('wordB')).trim(),difficulty:String(f.get('difficulty'))};if(normalize(data.wordA)===normalize(data.wordB))return toast('Kedua kata harus berbeda.');if(editing.id)Object.assign(c(editing.id),data);else db.cards.push({id:`D${String(db.cardSeq++).padStart(3,'0')}`,...data});cardDeck=[]}save();E.formDialog.close();renderManage();render();beep(720,.05);toast('Tersimpan.')}
function exportData(){const b=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='miau-secret-word-duel-data.json';a.click();URL.revokeObjectURL(a.href)}
async function importData(e){try{const x=JSON.parse(await e.target.files[0].text());if(!Array.isArray(x.players)||!Array.isArray(x.cards)||!x.cards.every(y=>y.id&&y.category&&y.wordA&&y.wordB))throw 0;db=x;db.theme||='light';db.sound??=true;db.playerSeq||=Math.max(0,...db.players.map(y=>Number(String(y.id).replace(/\D/g,''))||0))+1;db.cardSeq||=Math.max(0,...db.cards.map(y=>Number(String(y.id).replace(/\D/g,''))||0))+1;cardDeck=[];save();applyTheme();renderManage();render();toast('Import berhasil.')}catch{toast('JSON tidak valid.')}e.target.value=''}

E.manageBtn.onclick=()=>{renderManage();E.manageDialog.showModal()};document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{manageTab=t.dataset.tab;renderManage()});E.formCloseBtn.onclick=E.formCancelBtn.onclick=()=>E.formDialog.close();E.themeBtn.onclick=()=>{db.theme=db.theme==='dark'?'light':'dark';save();applyTheme()};E.soundBtn.onclick=()=>{db.sound=!db.sound;save();applyTheme();beep(700,.05)};
applyTheme();render();
